/* Generated By:JavaCC: Do not edit this line. SNL.java */
public class SNL implements SNLConstants {

  public static boolean verbose;

  /*public SNL (String s)  {	this((Reader)(new StringReader(s)));
  }*/

  public static void main(String args []) {
    //CHECK ARGUMENTS
        if (args.length == 0) {
            System.out.println("No input given");
            //  SNL snlParser = new SNL(System.in);
            return;
        } else if(args.length <= 2){
                System.out.println("Reading from file:" + args[0] + "...");
                //Checks verbose option
                if((args.length == 2) && (args[1].compareTo("verbose") == 0))
                        verbose = true;
                else
                        verbose = false;
                //Starts the parser
                try {
                SNL parser = new SNL(new java.io.FileInputStream(args[0]));
                parser.compilation_unit();
                        System.out.println("Parsing complete");
            } catch (java.io.FileNotFoundException e) {
                System.out.println("The File " + args[0] + " has not been found");
                return;
           //Catch Parsing Exceptions
                } catch (ParseException e2) {
                        //e2.printStackTrace();
                System.err.println("Parse error: " + e2.getMessage());
                } catch (TokenMgrError e1) {
                        //e1.printStackTrace();
                System.err.println("Token error: " + e1.getMessage());
                }

        } else {
            System.out.println("Wrong number of parameters. Paramater 1: input file. Parameter 2 (optional): verbose (1,0)");
            return;
        }
  }

/* __ __ REMARKS & CHANGES __ __ */

/* __ SUBJECTS __ */
/* This is not necesary, it must be changed in the grammar*/
/* __ OPERATORS __ */
//this way of declaring the operators might be the solution for the LL(1) problem, it should also increase efficiency
//The syntactical analyzer only needs to call expression operator, logical operator or concatenation operator
//expression_operator(+,-,*,/,+=,-=,*=,/=, and any combination with natural language)
//logical_operator(<,>,=,!=,==,<=, >= and any combination with natural language)
//comparison_operator (||, &&, or)
//PARENTHESIS ARE NOT INCLUDED !!!!
/*It might be better that the syntactical analyzer is on charge of this part, allowing nested brackets*/
/* __ UNUSED TOKENS __*/
//TOKEN [IGNORE_CASE] :
//{  
// <VALUE_OF : ("the" "value" "of") >// <ASSIGN : ( < SYMBOLIC_EQUALS > | < LANGUAGE_EQUALS >< TO > ) >
// <COMPLEX_OPERATION : "complex" "operation" >
//}
/*__ __ -------------------- __ __*/

/* __ -_-Syntactical Analyzer-_- __*/


/*
 *Prepares the grammar import and packages statements (Extracted from Java Grammar)
 * 
 * //compilation_unit : PACKAGE_STATEMENT? IMPORT_STATEMENT* TYPE_DECLARATION+
 *
 *IMPORT_STATEMENTS has been disabled for simplicity
 *
 *	("package" CLASS_ID ";")? class_declaration+
 */
  static final public void compilation_unit() throws ParseException {
  if(verbose) System.out.println("Start compilation_unit");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PACKAGE_STATEMENT:
      jj_consume_token(PACKAGE_STATEMENT);
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    label_1:
    while (true) {
      class_declaration();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ABSTRACT_MOD:
      case FINAL_MOD:
      case CLASS:
      case SUBJECT:
      case SUBJECT_3rd:
      case VISIBILITY:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
  }

/*
 *	creation_sentence? ("public"|"private"|"protected")? ("final"|"abstract")? "class" CLASS_ID field_declaration+ "end-class"
 */
  static final public void class_declaration() throws ParseException {
  if(verbose) System.out.println("Starts class_declaration");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUBJECT:
    case SUBJECT_3rd:
      creation_sentence();
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VISIBILITY:
      jj_consume_token(VISIBILITY);
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ABSTRACT_MOD:
    case FINAL_MOD:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FINAL_MOD:
        jj_consume_token(FINAL_MOD);
        break;
      case ABSTRACT_MOD:
        jj_consume_token(ABSTRACT_MOD);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(CLASS);
    jj_consume_token(CLASS_ID);
    label_2:
    while (true) {
      field_declaration();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS_METHOD_CONNECTOR:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_2;
      }
    }
    jj_consume_token(END_CLASS);
  }

/*
 *	"." creation_sentence? ("public"|"private"|"protected")? ("static")? ("final")? (constructor_declaration | method_declaration | variable_list)
 */
  static final public void field_declaration() throws ParseException {
  if(verbose) System.out.println("Starts field_declaration");
    jj_consume_token(CLASS_METHOD_CONNECTOR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUBJECT:
    case SUBJECT_3rd:
      creation_sentence();
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VISIBILITY:
      jj_consume_token(VISIBILITY);
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STATIC_MOD:
      jj_consume_token(STATIC_MOD);
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FINAL_MOD:
      jj_consume_token(FINAL_MOD);
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONSTRUCTOR:
      constructor_declaration();
      break;
    case TYPE_SPECIAL:
    case VOID:
    case CLASS_ID:
      method_declaration();
      break;
    case VARIABLE:
      variable_list();
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* __ CONSTRUCTOR, METHOD, VARIABLES (attributes) __ */
/*
 * The constructor must have only access modifiers
 *
 *	"constructor" ID parameter_list() ':' statement_list "end-constructor"
 */
  static final public void constructor_declaration() throws ParseException {
  if(verbose) System.out.println("Starts contructor_declaration");
    jj_consume_token(CONSTRUCTOR);
    jj_consume_token(CLASS_ID);
    parameter_list();
    jj_consume_token(METHOD_STATEMENT_CONNECTOR);
    statement_list();
    jj_consume_token(END_CONSTRUCTOR);
  }

/*
 * ("method"|"function) ID '(' ( parameter ("," parameter)* )? ')' ':' statement_list ("end-method"|"end-funtion")
 */
  static final public void method_declaration() throws ParseException {
  if(verbose) System.out.println("Starts method_declaration");
    type();
    jj_consume_token(METHOD);
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARRAY_TOKEN:
      jj_consume_token(ARRAY_TOKEN);
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
    parameter_list();
    jj_consume_token(METHOD_STATEMENT_CONNECTOR);
    statement_list();
    jj_consume_token(END_METHOD);
  }

/*
 * ("variable"|"variables") variable_declaration ("," variable_declaration)*
 */
  static final public void variable_list() throws ParseException {
  if(verbose) System.out.println("Starts variable_list");
    jj_consume_token(VARIABLE);
    variable_declaration();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LIST_CONNECTOR:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_3;
      }
      jj_consume_token(LIST_CONNECTOR);
      variable_declaration();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END_VARIABLE:
      jj_consume_token(END_VARIABLE);
      break;
    default:
      jj_la1[14] = jj_gen;
      ;
    }
  }

/*
 * ("boolean" | "byte" | "int" |...| CLASS_ID) ID []* variable_init?
 */
  static final public void variable_declaration() throws ParseException {
  if(verbose) System.out.println("Starts variable_declaration");
    type();
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARRAY_TOKEN:
      jj_consume_token(ARRAY_TOKEN);
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUALS:
      variable_init();
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
  }

/*
 * ("equals" | "=") (expression | array_values)
 */
  static final public void variable_init() throws ParseException {
  if(verbose) System.out.println("Starts variable_init");
    jj_consume_token(EQUALS);
    variable_initializer();
  }

/*
 * (expression | array_values)
 */
  static final public void variable_initializer() throws ParseException {
  if(verbose) System.out.println("Starts variable_initializer");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NEW:
    case READ:
    case UNARY_OPERATOR:
    case MINUS:
    case BOOLEAN_TOKEN:
    case EXPRESSION_MODIFIER:
    case INTEGER_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
    case ID:
    case 145:
      expression();
      break;
    case 149:
      array_init();
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*
 * needed for local variables, called from statement
 * creation_sentence? variable_list
 */
  static final public void variable_declaration_statement() throws ParseException {
  if(verbose) System.out.println("Starts statement_list");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUBJECT:
    case SUBJECT_3rd:
      creation_sentence();
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    variable_list();
  }

/* __ STATEMENTS __ */

/*
 * statement (';' statement)*
 */
  static final public void statement_list() throws ParseException {
  if(verbose) System.out.println("Starts statement_list");
    statement();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STATEMENT_CONNECTOR:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_4;
      }
      jj_consume_token(STATEMENT_CONNECTOR);
      statement();
    }
  }

/*
 * variable_list | expression | if_statement | while_statement | print_statement | read_statement | return_statement
 */
  static final public void statement() throws ParseException {
  if(verbose) System.out.println("Starts statement");
    if (jj_2_1(4)) {
      variable_declaration_statement();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NEW:
      case READ:
      case UNARY_OPERATOR:
      case MINUS:
      case BOOLEAN_TOKEN:
      case EXPRESSION_MODIFIER:
      case INTEGER_LITERAL:
      case STRING_LITERAL:
      case CHAR_LITERAL:
      case ID:
      case 145:
        expression();
        break;
      default:
        jj_la1[20] = jj_gen;
        if (jj_2_2(4)) {
          if_statement();
        } else if (jj_2_3(4)) {
          while_statement();
        } else if (jj_2_4(4)) {
          print_statement();
        } else if (jj_2_5(4)) {
          return_statement();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

/* __ IF __ */

/*
 * control_sentence? if_expression statement_list else_expression* "end-if"
 */
  static final public void if_statement() throws ParseException {
  if(verbose) System.out.println("Starts if_statement");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUBJECT:
    case SUBJECT_3rd:
      control_sentence();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    if_expression();
    statement_list();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_5;
      }
      else_expression();
    }
    jj_consume_token(END_IF);
  }

/*
 * "if" '(' logical_expression ')' "then"
 */
  static final public void if_expression() throws ParseException {
  if(verbose) System.out.println("Starts if_expression");
    jj_consume_token(IF);
    jj_consume_token(145);
    logical_expression();
    jj_consume_token(146);
    jj_consume_token(THEN);
  }

/*
 * "else" if_expression? statement_list 
 */
  static final public void else_expression() throws ParseException {
  if(verbose) System.out.println("Starts else_expression");
    jj_consume_token(ELSE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
      if_expression();
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    statement_list();
  }

/* __ WHILE __ */

/*
 * "while" '(' logical_expression ')' "then" statement_list "end-while"
 *
 * This statement does not use any natural language expression
 *
 */
  static final public void while_statement() throws ParseException {
  if(verbose) System.out.println("Starts while_statement");
    jj_consume_token(WHILE);
    jj_consume_token(145);
    logical_expression();
    jj_consume_token(146);
    jj_consume_token(THEN);
    statement_list();
    jj_consume_token(END_WHILE);
  }

/* __ PRINT __ */

/*
 * print_sentence '(' expression ')'
 */
  static final public void print_statement() throws ParseException {
  if(verbose) System.out.println("Starts print_statement");
    print_sentence();
    expression();
  }

/* __ READ __ */

/*
 * read_sentence '(' expression ')'
 *
 * not yet implemented 
 */
//void read_statement():
//{ if(verbose) System.out.println("Starts read_statement");}
//{
//	 read_sentence() "(" expression() ")" 
//}

/* __ RETURN __ */

/*
 * return_sentence expression
 *
 * ÁÁÁ Semantic analyzer must check the return type !!!
 */
  static final public void return_statement() throws ParseException {
  if(verbose) System.out.println("Starts return_statement");
    return_sentence();
    expression();
  }

/* __ EXPRESSIONS __*/

/* __ LOGICAL EXPRESSIONS __ */

/* comparison_expression | '(' comparison_expression ')' // allows nested brackets */
/*void logical_expression():
{ if(verbose) System.out.println("Starts logical_expression");}
{
  comparison_expression()
}*/ //WARNING not needed, deleted the parenthesis alternative

/* (expression ("=="|"!="|">"| ... |"equals"|"greater or equals"|...) expression) link_expression? */
  static final public void logical_expression() throws ParseException {
  if(verbose) System.out.println("Starts comparison_expression");
    expression();
    jj_consume_token(COMPARATOR);
    expression();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LINKER:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_6;
      }
      jj_consume_token(LINKER);
      logical_expression();
    }
  }

  //WARNING CHANGED !!! (Added <LINKER > logical_expression

/* (( "||" | "&&") logical_expression)+ */
  static final public void link_expression() throws ParseException {
  if(verbose) System.out.println("Starts link_expression");
    jj_consume_token(LINKER);
    logical_expression();
  }

/* __ EXPRESSION __ */

//Is necesary to divide the expression in order to delete the left recursion

/* simple_expression? complex_expression */
  static final public void expression() throws ParseException {
  if(verbose) System.out.println("Starts expression");
    simple_expression();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT_NOTATION:
      case OPERATOR:
      case UNARY_OPERATOR:
      case EQUALS:
      case 147:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_7;
      }
      complex_expression();
    }
  }

/* __ SIMPLE __ */
/*
 * '(' casting_expression | creating_expression | literal_expression | "null""this""super" | ID  (argument_list) | ("-""--""++""increment""decrement") expression | "true""false" | "read" 
 * casting_expression, also allows the nested brackets.
 * in ID (argument_list)? is needed for the method calls
 */
  static final public void simple_expression() throws ParseException {
  if(verbose) System.out.println("Starts simple_expression");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 145:
      jj_consume_token(145);
      casting_expression();
      break;
    case NEW:
      creating_expression();
      break;
    case INTEGER_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
      literal_expression();
      break;
    case EXPRESSION_MODIFIER:
      jj_consume_token(EXPRESSION_MODIFIER);
      break;
    case ID:
      jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 145:
        argument_list();
        break;
      default:
        jj_la1[26] = jj_gen;
        ;
      }
      break;
    case UNARY_OPERATOR:
    case MINUS:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case UNARY_OPERATOR:
        jj_consume_token(UNARY_OPERATOR);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      expression();
      break;
    case BOOLEAN_TOKEN:
      jj_consume_token(BOOLEAN_TOKEN);
      break;
    case READ:
      jj_consume_token(READ);
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* expresion ')' | TYPE ')' expression */
  static final public void casting_expression() throws ParseException {
  if(verbose) System.out.println("Starts casting_expression");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NEW:
    case READ:
    case UNARY_OPERATOR:
    case MINUS:
    case BOOLEAN_TOKEN:
    case EXPRESSION_MODIFIER:
    case INTEGER_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
    case ID:
    case 145:
      expression();
      jj_consume_token(146);
      break;
    case TYPE_SPECIAL:
    case VOID:
    case CLASS_ID:
      type();
      jj_consume_token(146);
      expression();
      break;
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* NEW expression_specifier */
  static final public void creating_expression() throws ParseException {
  if(verbose) System.out.println("Starts creating_expression");
    jj_consume_token(NEW);
    expression_specifier();
  }

/* (CLASS_ID (' argument_list ')') | (TYPE_SPECIAL '[' expression ']') | '(' expression ')' */
  static final public void expression_specifier() throws ParseException {
  if(verbose) System.out.println("Starts expression_specifier");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CLASS_ID:
      jj_consume_token(CLASS_ID);
      argument_list();
      break;
    case TYPE_SPECIAL:
      jj_consume_token(TYPE_SPECIAL);
      jj_consume_token(147);
      expression();
      jj_consume_token(148);
      break;
    case 145:
      jj_consume_token(145);
      expression();
      jj_consume_token(146);
      break;
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* CONSTANT ("." CONSTANT)? | \" (CHAR_LITERAL)+ \" | \' any char except (\" \') \' */
  static final public void literal_expression() throws ParseException {
  if(verbose) System.out.println("Starts literal_expression");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      jj_consume_token(INTEGER_LITERAL);
      break;
    case STRING_LITERAL:
      jj_consume_token(STRING_LITERAL);
      break;
    case CHAR_LITERAL:
      jj_consume_token(CHAR_LITERAL);
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* __ COMPLEX EXPRESSION __*/

/*
 * numeric_expression | casting_expression | assing_expression | complex_expression | "++", "--", "increment", "decrement"
 */
  static final public void complex_expression() throws ParseException {
  if(verbose) System.out.println("Starts expression");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OPERATOR:
      numeric_expression();
      break;
    case DOT_NOTATION:
    case 147:
      post_expression();
      break;
    case EQUALS:
      assign_expression();
      break;
    case UNARY_OPERATOR:
      jj_consume_token(UNARY_OPERATOR);
      break;
    default:
      jj_la1[32] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* ("+","-", ..."plus","minus",...) expression */
  static final public void numeric_expression() throws ParseException {
  if(verbose) System.out.println("Starts numeric_expression");
    jj_consume_token(OPERATOR);
    expression();
  }

/* '[' expression ']' | "- >" expression ) */
  static final public void post_expression() throws ParseException {
  if(verbose) System.out.println("Starts post_expression");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 147:
      jj_consume_token(147);
      expression();
      jj_consume_token(148);
      break;
    case DOT_NOTATION:
      jj_consume_token(DOT_NOTATION);
      expression();
      break;
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

 /* EQUALS (expression) */
  static final public void assign_expression() throws ParseException {
  if(verbose) System.out.println("Starts assign_expression");
    jj_consume_token(EQUALS);
    expression();
  }

/* __ NATURAL LANGUAGE __*/
//Natural language clauses are easily extensible in the token list

/* __ CREATION __ */

/*
 * ("I", "you"...) ("need to", "want to" | "must", "shall") ("create", "define") ("also", "in addition") ("a", "the")
 * ("I", "you"...) (("needs to", "wants to" | "must", "shall") ("create", "define") | ("creates", "defines"))("also", "in addition") ("a", "the")
 */
  static final public void creation_sentence() throws ParseException {
  if(verbose) System.out.println("Starts creation_sentence");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUBJECT:
      jj_consume_token(SUBJECT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MODAL_VERB:
      case AUXILIAR_EXPRESSION:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AUXILIAR_EXPRESSION:
          jj_consume_token(AUXILIAR_EXPRESSION);
          break;
        case MODAL_VERB:
          jj_consume_token(MODAL_VERB);
          break;
        default:
          jj_la1[34] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[35] = jj_gen;
        ;
      }
      jj_consume_token(CREATION_VERB);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AUXILIAR_CONNECTOR:
        jj_consume_token(AUXILIAR_CONNECTOR);
        break;
      default:
        jj_la1[36] = jj_gen;
        ;
      }
      jj_consume_token(A_THE);
      break;
    case SUBJECT_3rd:
      jj_consume_token(SUBJECT_3rd);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MODAL_VERB:
      case AUXILIAR_EXPRESSION3:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AUXILIAR_EXPRESSION3:
          jj_consume_token(AUXILIAR_EXPRESSION3);
          break;
        case MODAL_VERB:
          jj_consume_token(MODAL_VERB);
          break;
        default:
          jj_la1[37] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(CREATION_VERB);
        break;
      case CREATION_VERB_3rd:
        jj_consume_token(CREATION_VERB_3rd);
        break;
      default:
        jj_la1[38] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AUXILIAR_CONNECTOR:
        jj_consume_token(AUXILIAR_CONNECTOR);
        break;
      default:
        jj_la1[39] = jj_gen;
        ;
      }
      jj_consume_token(A_THE);
      break;
    default:
      jj_la1[40] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* __ CONTROL __ */

/*
 * ("I", "you"...) ("need to", "want to" | "must", "shall") ("check", "verify") ("also", "in addition")
 * ("I", "you"...) (("needs to", "wants to" | "must", "shall") ("check", "verify") | ("checks", "verifies"))("also", "in addition")
 */
  static final public void control_sentence() throws ParseException {
  if(verbose) System.out.println("Starts control_sentence");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUBJECT:
      jj_consume_token(SUBJECT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MODAL_VERB:
      case AUXILIAR_EXPRESSION:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AUXILIAR_EXPRESSION:
          jj_consume_token(AUXILIAR_EXPRESSION);
          break;
        case MODAL_VERB:
          jj_consume_token(MODAL_VERB);
          break;
        default:
          jj_la1[41] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[42] = jj_gen;
        ;
      }
      jj_consume_token(CONTROL_VERB);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AUXILIAR_CONNECTOR:
        jj_consume_token(AUXILIAR_CONNECTOR);
        break;
      default:
        jj_la1[43] = jj_gen;
        ;
      }
      break;
    case SUBJECT_3rd:
      jj_consume_token(SUBJECT_3rd);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MODAL_VERB:
      case AUXILIAR_EXPRESSION3:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AUXILIAR_EXPRESSION3:
          jj_consume_token(AUXILIAR_EXPRESSION3);
          break;
        case MODAL_VERB:
          jj_consume_token(MODAL_VERB);
          break;
        default:
          jj_la1[44] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(CONTROL_VERB);
        break;
      case CONTROL_VERB_3rd:
        jj_consume_token(CONTROL_VERB_3rd);
        break;
      default:
        jj_la1[45] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AUXILIAR_CONNECTOR:
        jj_consume_token(AUXILIAR_CONNECTOR);
        break;
      default:
        jj_la1[46] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[47] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* __ PRINT __ */

/*
 * The print sentence is compulsory. But it can only contain the verb in order to simplify the sketched coding
 * ("print")
 * ("I", "you"...) ("need to", "want to" | "must", "shall") ("print") ("also", "in addition")
 * ("I", "you"...) (("needs to", "wants to" | "must", "shall") ("print") | ("prints"))("also", "in addition") 
 */
  static final public void print_sentence() throws ParseException {
  if(verbose) System.out.println("Starts print_sentence");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PRINT_VERB:
      jj_consume_token(PRINT_VERB);
      break;
    case SUBJECT:
      jj_consume_token(SUBJECT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MODAL_VERB:
      case AUXILIAR_EXPRESSION:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AUXILIAR_EXPRESSION:
          jj_consume_token(AUXILIAR_EXPRESSION);
          break;
        case MODAL_VERB:
          jj_consume_token(MODAL_VERB);
          break;
        default:
          jj_la1[48] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[49] = jj_gen;
        ;
      }
      jj_consume_token(PRINT_VERB);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AUXILIAR_CONNECTOR:
        jj_consume_token(AUXILIAR_CONNECTOR);
        break;
      default:
        jj_la1[50] = jj_gen;
        ;
      }
      break;
    case SUBJECT_3rd:
      jj_consume_token(SUBJECT_3rd);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MODAL_VERB:
      case AUXILIAR_EXPRESSION3:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AUXILIAR_EXPRESSION3:
          jj_consume_token(AUXILIAR_EXPRESSION3);
          break;
        case MODAL_VERB:
          jj_consume_token(MODAL_VERB);
          break;
        default:
          jj_la1[51] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(PRINT_VERB);
        break;
      case PRINT_VERB_3rd:
        jj_consume_token(PRINT_VERB_3rd);
        break;
      default:
        jj_la1[52] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AUXILIAR_CONNECTOR:
        jj_consume_token(AUXILIAR_CONNECTOR);
        break;
      default:
        jj_la1[53] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[54] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* __ READ __ */

/*
 *The read sentence is not needed because it is encapsulated as an expression, so it has no sense to include a phrase in an expression and no phrases for the rest of them.
 *In order to read and store the result in a variable the next expression should be used:
 *
 *String s = read
 */

/* __ RETURN __ */

/*
 * The return sentence is compulsory. But it can only contain the verb in order to simplify the sketched coding.
 * It can only be used in third person, if it stands alone the regular form will be used "return" instead the third person "returns"
 *
 * ("return")
 * ("I", "you"...) (("needs to", "wants to" | "must", "shall") ("return") | ("returns"))
 */
  static final public void return_sentence() throws ParseException {
  if(verbose) System.out.println("Starts return_sentence");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RETURN_VERB:
      jj_consume_token(RETURN_VERB);
      break;
    case SUBJECT_3rd:
      jj_consume_token(SUBJECT_3rd);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MODAL_VERB:
      case AUXILIAR_EXPRESSION3:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AUXILIAR_EXPRESSION3:
          jj_consume_token(AUXILIAR_EXPRESSION3);
          break;
        case MODAL_VERB:
          jj_consume_token(MODAL_VERB);
          break;
        default:
          jj_la1[55] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(RETURN_VERB);
        break;
      case RETURN_VERB_3rd:
        jj_consume_token(RETURN_VERB_3rd);
        break;
      default:
        jj_la1[56] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[57] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* __ AUXILIAR EXPRESSIONS __ */

/*
 * A parameter list can allways be empty '()'
 *
 * 	(' ( parameter ("," parameter)* )? ')'
 *
 *	The parameter list could be:
 * 		() - empty
 *		(parameter) - one element
 *		(parameter ,parameter ,parameter) -n elements
 *  The parameter list cannot:
 *		(, parameter) - start with connector
 *		(parameter parameter) - have parameters without connector 
 */
  static final public void parameter_list() throws ParseException {
  if(verbose) System.out.println("Starts parameter_list");
    jj_consume_token(145);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPE_SPECIAL:
    case VOID:
    case CLASS_ID:
      parameter();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LIST_CONNECTOR:
          ;
          break;
        default:
          jj_la1[58] = jj_gen;
          break label_8;
        }
        jj_consume_token(LIST_CONNECTOR);
        parameter();
      }
      break;
    default:
      jj_la1[59] = jj_gen;
      ;
    }
    jj_consume_token(146);
  }

/* TYPE ID ([])* */
  static final public void parameter() throws ParseException {
  if(verbose) System.out.println("Starts parameter");
    type();
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARRAY_TOKEN:
      jj_consume_token(ARRAY_TOKEN);
      break;
    default:
      jj_la1[60] = jj_gen;
      ;
    }
  }

/*
 * Is like a parameter list but with expressions instead parameters, 
 * much more complex
 *
 * (' ( expression ("," expression)* )? ')'
 */
  static final public void argument_list() throws ParseException {
  if(verbose) System.out.println("Starts argument_list");
    jj_consume_token(145);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NEW:
    case READ:
    case UNARY_OPERATOR:
    case MINUS:
    case BOOLEAN_TOKEN:
    case EXPRESSION_MODIFIER:
    case INTEGER_LITERAL:
    case STRING_LITERAL:
    case CHAR_LITERAL:
    case ID:
    case 145:
      expression();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LIST_CONNECTOR:
          ;
          break;
        default:
          jj_la1[61] = jj_gen;
          break label_9;
        }
        jj_consume_token(LIST_CONNECTOR);
        expression();
      }
      break;
    default:
      jj_la1[62] = jj_gen;
      ;
    }
    jj_consume_token(146);
  }

/*
 * ("equals" | "=") (expression | array_values)
 *
 * It can produce a list of expression or array expressions:
 * 	expresssion
 *  { expression }
 *	{ expression ,expression }
 *	{ expression ,{ expression ,expression } ,expression}
 *
 */
  static final public void array_init() throws ParseException {
  if(verbose) System.out.println("Starts array_init");
    jj_consume_token(149);
    variable_initializer();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LIST_CONNECTOR:
        ;
        break;
      default:
        jj_la1[63] = jj_gen;
        break label_10;
      }
      jj_consume_token(LIST_CONNECTOR);
      variable_initializer();
    }
    jj_consume_token(150);
  }

/* __ TOKEN EXPRESSIONS __*/
//Those are simple expressions that simplifies the grammar comprehension but cannot be stored in the lexical analyzer easily

/*  (TYPE_SPECIFIER | CLASS_ID) ([])* */
  static final public void type() throws ParseException {
  if(verbose) System.out.println("Starts parameter");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPE_SPECIAL:
    case CLASS_ID:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TYPE_SPECIAL:
        jj_consume_token(TYPE_SPECIAL);
        break;
      case CLASS_ID:
        jj_consume_token(CLASS_ID);
        break;
      default:
        jj_la1[64] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARRAY_TOKEN:
        jj_consume_token(ARRAY_TOKEN);
        break;
      default:
        jj_la1[65] = jj_gen;
        ;
      }
      break;
    case VOID:
      jj_consume_token(VOID);
      break;
    default:
      jj_la1[66] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_3R_73() {
    if (jj_scan_token(DOT_NOTATION)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_64() {
    if (jj_scan_token(145)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_71()) jj_scanpos = xsp;
    if (jj_scan_token(146)) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_18()) jj_scanpos = xsp;
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_67() {
    if (jj_scan_token(EQUALS)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(COMPARATOR)) return true;
    return false;
  }

  static private boolean jj_3R_59() {
    if (jj_3R_66()) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    }
    if (jj_scan_token(RETURN_VERB)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_69() {
    if (jj_scan_token(TYPE_SPECIAL)) return true;
    if (jj_scan_token(147)) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_72() {
    if (jj_scan_token(147)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_66() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) return true;
    }
    return false;
  }

  static private boolean jj_3R_43() {
    if (jj_3R_56()) return true;
    return false;
  }

  static private boolean jj_3R_65() {
    if (jj_scan_token(OPERATOR)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_3R_51()) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_3R_23()) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    if (jj_scan_token(SUBJECT_3rd)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_scan_token(50)) return true;
    }
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_16()) jj_scanpos = xsp;
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_scan_token(LIST_CONNECTOR)) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(49)) {
    jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    }
    return false;
  }

  static private boolean jj_3R_58() {
    if (jj_3R_65()) return true;
    return false;
  }

  static private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_scan_token(60)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    }
    if (jj_scan_token(PRINT_VERB)) return true;
    return false;
  }

  static private boolean jj_3R_45() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(60)) {
    jj_scanpos = xsp;
    if (jj_scan_token(61)) return true;
    }
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_39() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(65)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    }
    return false;
  }

  static private boolean jj_3R_56() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(132)) {
    jj_scanpos = xsp;
    if (jj_scan_token(133)) {
    jj_scanpos = xsp;
    if (jj_scan_token(134)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_42() {
    if (jj_3R_55()) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_62() {
    if (jj_3R_35()) return true;
    if (jj_scan_token(146)) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_68() {
    if (jj_scan_token(CLASS_ID)) return true;
    if (jj_3R_64()) return true;
    return false;
  }

  static private boolean jj_3R_63() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) {
    jj_scanpos = xsp;
    if (jj_3R_70()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_51() {
    if (jj_scan_token(EQUALS)) return true;
    return false;
  }

  static private boolean jj_3R_53() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    }
    if (jj_scan_token(CONTROL_VERB)) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_3R_21()) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_scan_token(SUBJECT_3rd)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) return true;
    }
    xsp = jj_scanpos;
    if (jj_scan_token(55)) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_scan_token(SUBJECT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_39()) jj_scanpos = xsp;
    if (jj_scan_token(PRINT_VERB)) return true;
    xsp = jj_scanpos;
    if (jj_scan_token(55)) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_57() {
    if (jj_3R_64()) return true;
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_63()) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_52() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(65)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    }
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_3R_35()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(39)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_49() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    }
    if (jj_scan_token(CREATION_VERB)) return true;
    return false;
  }

  static private boolean jj_3R_61() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(146)) return true;
    return false;
  }

  static private boolean jj_3R_54() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) return true;
    }
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(145)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_57()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_3R_46()) return true;
    return false;
  }

  static private boolean jj_3R_50() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_scan_token(135)) return true;
    }
    xsp = jj_scanpos;
    if (jj_scan_token(39)) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_35() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_scan_token(130)) return true;
    }
    return false;
  }

  static private boolean jj_3R_70() {
    if (jj_scan_token(145)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(VARIABLE)) return true;
    if (jj_3R_25()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_26()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_scan_token(30)) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_48() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(65)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    }
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_scan_token(145)) return true;
    if (jj_3R_54()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_scan_token(70)) {
    jj_scanpos = xsp;
    if (jj_scan_token(48)) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_scan_token(SUBJECT_3rd)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) return true;
    }
    xsp = jj_scanpos;
    if (jj_scan_token(55)) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_27() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) return true;
    }
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_scan_token(SUBJECT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_52()) jj_scanpos = xsp;
    if (jj_scan_token(CONTROL_VERB)) return true;
    xsp = jj_scanpos;
    if (jj_scan_token(55)) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_scan_token(SUBJECT_3rd)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) return true;
    }
    xsp = jj_scanpos;
    if (jj_scan_token(55)) jj_scanpos = xsp;
    if (jj_scan_token(A_THE)) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) return true;
    }
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_scan_token(SUBJECT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_48()) jj_scanpos = xsp;
    if (jj_scan_token(CREATION_VERB)) return true;
    xsp = jj_scanpos;
    if (jj_scan_token(55)) jj_scanpos = xsp;
    if (jj_scan_token(A_THE)) return true;
    return false;
  }

  static private boolean jj_3R_60() {
    if (jj_3R_67()) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_3R_30()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_71() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(145)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public SNLTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[67];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static private int[] jj_la1_4;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
      jj_la1_init_4();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x828000,0x0,0x0,0x28000,0x28000,0x200,0x0,0x0,0x10000,0x20000,0x22000000,0x0,0x800,0x40000000,0x0,0x0,0x0,0x0,0x1000,0x0,0x0,0x0,0x80000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x400000,0x400000,0x0,0x400000,0x400000,0x0,0x0,0x400000,0x400000,0x0,0x400000,0x400000,0x0,0x0,0x400000,0x400000,0x0,0x400000,0x400000,0x0,0x0,0x400000,0x400000,0x0,0x800,0x0,0x0,0x800,0x0,0x800,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x3000000,0x3000000,0x0,0x0,0x0,0x0,0x3000000,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x80,0x0,0x30010040,0x3000000,0x0,0x30010040,0x3000000,0x1,0x0,0x80000000,0x18080000,0x0,0x30000000,0x30010040,0x30010040,0x0,0x0,0x18080000,0x80000,0x0,0x0,0x800000,0x0,0x800,0x800000,0x3000000,0x0,0x0,0x800000,0x0,0x2000,0x800000,0x3000000,0x0,0x0,0x800000,0x0,0x8000,0x800000,0x3004000,0x0,0x40000,0x2020000,0x0,0x0,0x80,0x0,0x30010040,0x0,0x0,0x80,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x8,0x10,0x0,0x10,0x0,0x0,0x0,0x0,0x10,0x0,0x0,0x20,0x0,0x0,0x0,0x0,0x1,0xc0,0x0,0x0,0xc0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0xc0,0xe0,0x20,0x0,0x1,0x0,0x2,0x2,0x0,0x4,0x4,0x0,0x0,0x2,0x2,0x0,0x4,0x4,0x0,0x0,0x2,0x2,0x0,0x4,0x4,0x0,0x0,0x4,0x4,0x0,0x0,0x20,0x0,0x0,0xc0,0x0,0x20,0x0,0x20,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_4() {
      jj_la1_4 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x84,0x0,0x0,0x0,0x0,0x0,0x220170,0x0,0x0,0x20170,0x0,0x0,0x0,0x0,0x80000,0x20000,0x0,0x20170,0x201f4,0x20080,0x70,0x80000,0x80000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x84,0x0,0x0,0x20170,0x0,0x80,0x0,0x84,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[5];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public SNL(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SNL(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SNLTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 67; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 67; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public SNL(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SNLTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 67; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 67; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public SNL(SNLTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 67; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(SNLTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 67; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[151];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 67; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
          if ((jj_la1_4[i] & (1<<j)) != 0) {
            la1tokens[128+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 151; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 5; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
