/* Generated By:JavaCC: Do not edit this line. SNL.java */
public class SNL implements SNLConstants {

  public static boolean verbose;

  public static void main(String args []) {
        if (args.length == 0) {
            System.out.println("No input given");
            //  SNL snlParser = new SNL(System.in);
            return;
        } else if(args.length <= 2){
                System.out.println("Reading from file:" + args[0] + "...");
                //Checks verbose option
                if((args.length == 2) && (args[1].compareTo("verbose") == 0))
                        verbose = true;
                else
                        verbose = false;
                //Starts the parser
                try {
                SNL parser = new SNL(new java.io.FileInputStream(args[0]));
                parser.compilation_unit();
                        System.out.println("Parsing complete");
                //Catchs Exceptions
            } catch (java.io.FileNotFoundException e) {
                System.out.println("The File " + args[0] + " has not been found");
                return;
                } catch (TokenMgrError e1) {
                System.out.println("Token Exception");
                return;
                } catch (ParseException e2) {
                System.out.println("Parsing Exception");
                System.out.println("Read Token: "+token.image);
                return;
           }

        } else {
            System.out.println("Wrong number of parameters. Paramater 1: input file. Parameter 2 (optional): verbose (1,0)");
            return;
        }

        //Parser begin

  }

/* __ __ REMARKS & CHANGES __ __ */

/* __ SUBJECTS __ */
/* This is not necesary, it must be changed in the grammar*/
/* __ OPERATORS __ */
//this way of declaring the operators might be the solution for the LL(1) problem, it should also increase efficiency
//The syntactical analyzer only needs to call expression operator, logical operator or concatenation operator
//expression_operator(+,-,*,/,+=,-=,*=,/=, and any combination with natural language)
//logical_operator(<,>,=,!=,==,<=, >= and any combination with natural language)
//comparison_operator (||, &&, or)
//PARENTHESIS ARE NOT INCLUDED !!!!
/*It might be better that the syntactical analyzer is on charge of this part, allowing nested brackets*/
/* __ UNUSED TOKENS __*/
//TOKEN [IGNORE_CASE] :
//{  
// <VALUE_OF : ("the" "value" "of") >// <ASSIGN : ( < SYMBOLIC_EQUALS > | < LANGUAGE_EQUALS >< TO > ) >
// <COMPLEX_OPERATION : "complex" "operation" >
//}
/*__ __ -------------------- __ __*/

/* __ -_-Syntactical Analyzer-_- __*/


/*
 *Prepares the grammar import and packages statements (Extracted from Java Grammar)
 * 
 * //compilation_unit : PACKAGE_STATEMENT? IMPORT_STATEMENT* TYPE_DECLARATION+
 *
 *IMPORT_STATEMENTS has been disabled for simplicity
 *
 *	("package" CLASS_ID ";")? class_declaration+
 */
  static final public void compilation_unit() throws ParseException {
    trace_call("compilation_unit");
    try {
  if(verbose) System.out.println("Start compilation_unit");
      if (jj_2_1(2)) {
        jj_consume_token(PACKAGE_STATEMENT);
      } else {
        ;
      }
      label_1:
      while (true) {
        class_declaration();
        if (jj_2_2(2)) {
          ;
        } else {
          break label_1;
        }
      }
    } finally {
      trace_return("compilation_unit");
    }
  }

/*
 *	creation_sentence? ("public"|"private"|"protected")? ("final"|"abstract")? "class" CLASS_ID field_declaration+ "end-class"
 */
  static final public void class_declaration() throws ParseException {
    trace_call("class_declaration");
    try {
  if(verbose) System.out.println("Starts class_declaration");
      if (jj_2_3(2)) {
        creation_sentence();
      } else {
        ;
      }
      if (jj_2_4(2)) {
        jj_consume_token(VISIBILITY);
      } else {
        ;
      }
      if (jj_2_7(2)) {
        if (jj_2_5(2)) {
          jj_consume_token(FINAL_MOD);
        } else if (jj_2_6(2)) {
          jj_consume_token(ABSTRACT_MOD);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      } else {
        ;
      }
      jj_consume_token(CLASS);
      jj_consume_token(CLASS_ID);
      label_2:
      while (true) {
        field_declaration();
        if (jj_2_8(2)) {
          ;
        } else {
          break label_2;
        }
      }
      jj_consume_token(END_CLASS);
    } finally {
      trace_return("class_declaration");
    }
  }

/*
 *	"." creation_sentence? ("public"|"private"|"protected")? ("static")? ("final")? (constructor_declaration | method_declaration | variable_list)
 */
  static final public void field_declaration() throws ParseException {
    trace_call("field_declaration");
    try {
  if(verbose) System.out.println("Starts field_declaration");
      jj_consume_token(CLASS_METHOD_CONNECTOR);
      if (jj_2_9(2)) {
        creation_sentence();
      } else {
        ;
      }
      if (jj_2_10(2)) {
        jj_consume_token(VISIBILITY);
      } else {
        ;
      }
      if (jj_2_11(2)) {
        jj_consume_token(STATIC_MOD);
      } else {
        ;
      }
      if (jj_2_12(2)) {
        jj_consume_token(FINAL_MOD);
      } else {
        ;
      }
      if (jj_2_13(2)) {
        constructor_declaration();
      } else if (jj_2_14(2)) {
        method_declaration();
      } else if (jj_2_15(2)) {
        variable_list();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("field_declaration");
    }
  }

/* __ CONSTRUCTOR, METHOD, VARIABLES (attributes) __ */
/*
 * The constructor must have only access modifiers
 *
 *	"constructor" ID parameter_list() ':' statement_list "end-constructor"
 */
  static final public void constructor_declaration() throws ParseException {
    trace_call("constructor_declaration");
    try {
  if(verbose) System.out.println("Starts contructor_declaration");
      jj_consume_token(CONSTRUCTOR);
      jj_consume_token(ID);
      parameter_list();
      jj_consume_token(METHOD_STATEMENT_CONNECTOR);
      statement_list();
      jj_consume_token(END_CONSTRUCTOR);
    } finally {
      trace_return("constructor_declaration");
    }
  }

/*
 * ("method"|"function) ID '(' ( parameter ("," parameter)* )? ')' ':' statement_list ("end-method"|"end-funtion")
 */
  static final public void method_declaration() throws ParseException {
    trace_call("method_declaration");
    try {
  if(verbose) System.out.println("Starts method_declaration");
      jj_consume_token(METHOD);
      jj_consume_token(TYPE);
      jj_consume_token(ID);
      if (jj_2_16(2)) {
        jj_consume_token(ARRAY_TOKEN);
      } else {
        ;
      }
      parameter_list();
      jj_consume_token(METHOD_STATEMENT_CONNECTOR);
      statement_list();
      jj_consume_token(END_METHOD);
    } finally {
      trace_return("method_declaration");
    }
  }

/*
 * ("variable"|"variables") variable_declaration ("," variable_declaration)* ("end-variable"|"end-variables")
 */
  static final public void variable_list() throws ParseException {
    trace_call("variable_list");
    try {
  if(verbose) System.out.println("Starts variable_list");
      jj_consume_token(VARIABLE);
      variable_declaration();
      label_3:
      while (true) {
        if (jj_2_17(2)) {
          ;
        } else {
          break label_3;
        }
        jj_consume_token(LIST_CONNECTOR);
        variable_declaration();
      }
      jj_consume_token(END_VARIABLE);
    } finally {
      trace_return("variable_list");
    }
  }

/*
 * ("boolean" | "byte" | "int" |...| CLASS_ID) ID []* variable_init?
 */
  static final public void variable_declaration() throws ParseException {
    trace_call("variable_declaration");
    try {
  if(verbose) System.out.println("Starts variable_declaration");
      jj_consume_token(TYPE);
      jj_consume_token(ID);
      if (jj_2_18(2)) {
        jj_consume_token(ARRAY_TOKEN);
      } else {
        ;
      }
      if (jj_2_19(2)) {
        variable_init();
      } else {
        ;
      }
    } finally {
      trace_return("variable_declaration");
    }
  }

/*
 * ("equals" | "=") (expression | array_values)
 */
  static final public void variable_init() throws ParseException {
    trace_call("variable_init");
    try {
  if(verbose) System.out.println("Starts variable_init");
      jj_consume_token(EQUALS);
      variable_initializer();
    } finally {
      trace_return("variable_init");
    }
  }

/*
 * (expression | array_values)
 */
  static final public void variable_initializer() throws ParseException {
    trace_call("variable_initializer");
    try {
  if(verbose) System.out.println("Starts variable_initializer");
      if (jj_2_20(2)) {
        expression();
      } else if (jj_2_21(2)) {
        array_init();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("variable_initializer");
    }
  }

/*
 * needed for local variables, called from statement
 * creation_sentence? ("boolean" | ... | CLASS_ID) variable_list
 */
  static final public void variable_declaration_statement() throws ParseException {
    trace_call("variable_declaration_statement");
    try {
  if(verbose) System.out.println("Starts statement_list");
      if (jj_2_22(2)) {
        creation_sentence();
      } else {
        ;
      }
      jj_consume_token(TYPE);
      variable_list();
    } finally {
      trace_return("variable_declaration_statement");
    }
  }

/* __ STATEMENTS __ */

/*
 * statement (';' statement)*
 */
  static final public void statement_list() throws ParseException {
    trace_call("statement_list");
    try {
  if(verbose) System.out.println("Starts statement_list");
      statement();
      label_4:
      while (true) {
        if (jj_2_23(2)) {
          ;
        } else {
          break label_4;
        }
        jj_consume_token(STATEMENT_CONNECTOR);
        statement();
      }
    } finally {
      trace_return("statement_list");
    }
  }

/*
 * variable_list | expression | if_statement | while_statement | print_statement | read_statement | return_statement
 */
  static final public void statement() throws ParseException {
    trace_call("statement");
    try {
  if(verbose) System.out.println("Starts statement");
      if (jj_2_24(3)) {
        variable_declaration_statement();
      } else if (jj_2_25(2)) {
        expression();
      } else if (jj_2_26(3)) {
        if_statement();
      } else if (jj_2_27(3)) {
        while_statement();
      } else if (jj_2_28(3)) {
        print_statement();
      } else if (jj_2_29(2)) {
        return_statement();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("statement");
    }
  }

/* __ IF __ */

/*
 * control_sentence? if_expression statement_list else_expression* "end-if"
 */
  static final public void if_statement() throws ParseException {
    trace_call("if_statement");
    try {
  if(verbose) System.out.println("Starts if_statement");
      if (jj_2_30(2)) {
        control_sentence();
      } else {
        ;
      }
      if_expression();
      statement_list();
      label_5:
      while (true) {
        if (jj_2_31(2)) {
          ;
        } else {
          break label_5;
        }
        else_expression();
      }
      jj_consume_token(END_IF);
    } finally {
      trace_return("if_statement");
    }
  }

/*
 * "if" '(' logical_expression ')' "then"
 */
  static final public void if_expression() throws ParseException {
    trace_call("if_expression");
    try {
  if(verbose) System.out.println("Starts if_expression");
      jj_consume_token(IF);
      jj_consume_token(142);
      logical_expression();
      jj_consume_token(143);
      jj_consume_token(THEN);
    } finally {
      trace_return("if_expression");
    }
  }

/*
 * "else" if_expression? statement_list 
 */
  static final public void else_expression() throws ParseException {
    trace_call("else_expression");
    try {
  if(verbose) System.out.println("Starts else_expression");
      jj_consume_token(ELSE);
      if (jj_2_32(2)) {
        if_expression();
      } else {
        ;
      }
      statement_list();
    } finally {
      trace_return("else_expression");
    }
  }

/* __ WHILE __ */

/*
 * "while" '(' logical_expression ')' "then" statement_list "end-while"
 *
 * This statement does not use any natural language expression
 *
 */
  static final public void while_statement() throws ParseException {
    trace_call("while_statement");
    try {
  if(verbose) System.out.println("Starts while_statement");
      jj_consume_token(WHILE);
      jj_consume_token(142);
      logical_expression();
      jj_consume_token(143);
      jj_consume_token(THEN);
      statement_list();
      jj_consume_token(END_WHILE);
    } finally {
      trace_return("while_statement");
    }
  }

/* __ PRINT __ */

/*
 * print_sentence '(' expression ')'
 */
  static final public void print_statement() throws ParseException {
    trace_call("print_statement");
    try {
  if(verbose) System.out.println("Starts print_statement");
      print_sentence();
      jj_consume_token(142);
      expression();
      jj_consume_token(143);
    } finally {
      trace_return("print_statement");
    }
  }

/* __ READ __ */

/*
 * read_sentence '(' expression ')'
 *
 * not yet implemented 
 */
//void read_statement():
//{ if(verbose) System.out.println("Starts read_statement");}
//{
//	 read_sentence() "(" expression() ")" 
//}

/* __ RETURN __ */

/*
 * return_sentence expression
 *
 * ÁÁÁ Semantic analyzer must check the return type !!!
 */
  static final public void return_statement() throws ParseException {
    trace_call("return_statement");
    try {
  if(verbose) System.out.println("Starts return_statement");
      return_sentence();
      expression();
    } finally {
      trace_return("return_statement");
    }
  }

/* __ EXPRESSIONS __*/

/* __ LOGICAL EXPRESSIONS __ */

/* comparison_expression | '(' comparison_expression ')' // allows nested brackets */
  static final public void logical_expression() throws ParseException {
    trace_call("logical_expression");
    try {
  if(verbose) System.out.println("Starts logical_expression");
      if (jj_2_33(3)) {
        comparison_expression();
      } else if (jj_2_34(3)) {
        jj_consume_token(142);
        comparison_expression();
        jj_consume_token(143);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("logical_expression");
    }
  }

/* (expression ("=="|"!="|">"| ... |"equals"|"greater or equals"|...) expression) link_expression? */
  static final public void comparison_expression() throws ParseException {
    trace_call("comparison_expression");
    try {
  if(verbose) System.out.println("Starts comparison_expression");
      expression();
      jj_consume_token(COMPARATOR);
      expression();
      link_expression();
    } finally {
      trace_return("comparison_expression");
    }
  }

/* (( "||" | "&&") logical_expression)+ */
  static final public void link_expression() throws ParseException {
    trace_call("link_expression");
    try {
  if(verbose) System.out.println("Starts link_expression");
      label_6:
      while (true) {
        if (jj_2_35(2)) {
          ;
        } else {
          break label_6;
        }
        jj_consume_token(LINKER);
        logical_expression();
      }
    } finally {
      trace_return("link_expression");
    }
  }

/* __ EXPRESSION __ */

//Is necesary to divide the expression in order to delete the left recursion

/* simple_expression? complex_expression */
  static final public void expression() throws ParseException {
    trace_call("expression");
    try {
  if(verbose) System.out.println("Starts expression");
      if (jj_2_36(2)) {
        simple_expression();
      } else {
        ;
      }
      complex_expression();
    } finally {
      trace_return("expression");
    }
  }

/* __ SIMPLE __ */
/*
 * '(' casting_expression | creating_expression | literal_expression | "null""this""super" | ID | "-""--""++""increment""decrement" | "read"
 * casting_expression, also allows the nested brackets
 */
  static final public void simple_expression() throws ParseException {
    trace_call("simple_expression");
    try {
  if(verbose) System.out.println("Starts simple_expression");
      if (jj_2_39(2)) {
        jj_consume_token(142);
        casting_expression();
      } else if (jj_2_40(2)) {
        creating_expression();
      } else if (jj_2_41(2)) {
        literal_expression();
      } else if (jj_2_42(2)) {
        jj_consume_token(EXPRESSION_MODIFIER);
      } else if (jj_2_43(2)) {
        jj_consume_token(ID);
      } else if (jj_2_44(2)) {
        if (jj_2_37(2)) {
          jj_consume_token(UNARY_OPERATOR);
        } else if (jj_2_38(2)) {
          jj_consume_token(MINUS);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      } else if (jj_2_45(2)) {
        jj_consume_token(READ);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("simple_expression");
    }
  }

/* expresion ')' | TYPE ')' expression */
  static final public void casting_expression() throws ParseException {
    trace_call("casting_expression");
    try {
  if(verbose) System.out.println("Starts casting_expression");
      if (jj_2_46(2)) {
        expression();
        jj_consume_token(143);
      } else if (jj_2_47(2)) {
        jj_consume_token(TYPE);
        jj_consume_token(143);
        expression();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("casting_expression");
    }
  }

/* NEW expression_specifier */
  static final public void creating_expression() throws ParseException {
    trace_call("creating_expression");
    try {
  if(verbose) System.out.println("Starts creating_expression");
      jj_consume_token(NEW);
      expression_specifier();
    } finally {
      trace_return("creating_expression");
    }
  }

/* (CLASS_ID (' argument_list ')') | (TYPE_SPECIAL '[' expression ']') | '(' expression ')' */
  static final public void expression_specifier() throws ParseException {
    trace_call("expression_specifier");
    try {
  if(verbose) System.out.println("Starts expression_specifier");
      if (jj_2_48(2)) {
        jj_consume_token(CLASS_ID);
        argument_list();
      } else if (jj_2_49(2)) {
        jj_consume_token(TYPE_SPECIAL);
        jj_consume_token(144);
        expression();
        jj_consume_token(145);
      } else if (jj_2_50(2)) {
        jj_consume_token(142);
        expression();
        jj_consume_token(143);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("expression_specifier");
    }
  }

/* CONSTANT ("." CONSTANT)? | \" (CHAR_LITERAL)+ \" | \' any char except (\" \') \' */
  static final public void literal_expression() throws ParseException {
    trace_call("literal_expression");
    try {
  if(verbose) System.out.println("Starts literal_expression");
      if (jj_2_51(2)) {
        jj_consume_token(INTEGER_LITERAL);
      } else if (jj_2_52(2)) {
        jj_consume_token(STRING_LITERAL);
      } else if (jj_2_53(2)) {
        jj_consume_token(CHAR_LITERAL);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("literal_expression");
    }
  }

/* __ COMPLEX EXPRESSION __*/

/*
 * numeric_expression | casting_expression | assing_expression | complex_expression | "++", "--", "increment", "decrement"
 */
  static final public void complex_expression() throws ParseException {
    trace_call("complex_expression");
    try {
  if(verbose) System.out.println("Starts expression");
      if (jj_2_54(2)) {
        numeric_expression();
      } else if (jj_2_55(2)) {
        post_expression();
      } else if (jj_2_56(2)) {
        assign_expression();
      } else if (jj_2_57(2)) {
        jj_consume_token(UNARY_OPERATOR);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("complex_expression");
    }
  }

/* ("+","-", ..."plus","minus",...) expression */
  static final public void numeric_expression() throws ParseException {
    trace_call("numeric_expression");
    try {
  if(verbose) System.out.println("Starts numeric_expression");
      jj_consume_token(OPERATOR);
      expression();
    } finally {
      trace_return("numeric_expression");
    }
  }

/* '[' expression ']' | "- >" expression ) */
  static final public void post_expression() throws ParseException {
    trace_call("post_expression");
    try {
  if(verbose) System.out.println("Starts post_expression");
      if (jj_2_58(2)) {
        jj_consume_token(144);
        expression();
        jj_consume_token(145);
      } else if (jj_2_59(2)) {
        jj_consume_token(DOT_NOTATION);
        expression();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("post_expression");
    }
  }

 /* EQUALS (expression) */
  static final public void assign_expression() throws ParseException {
    trace_call("assign_expression");
    try {
  if(verbose) System.out.println("Starts assign_expression");
      jj_consume_token(EQUALS);
      expression();
    } finally {
      trace_return("assign_expression");
    }
  }

/* __ NATURAL LANGUAGE __*/
//Natural language clauses are easily extensible in the token list

/* __ CREATION __ */

/*
 * ("I", "you"...) ("need to", "want to" | "must", "shall") ("create", "define") ("also", "in addition") ("a", "the")
 * ("I", "you"...) (("needs to", "wants to" | "must", "shall") ("create", "define") | ("creates", "defines"))("also", "in addition") ("a", "the")
 */
  static final public void creation_sentence() throws ParseException {
    trace_call("creation_sentence");
    try {
  if(verbose) System.out.println("Starts creation_sentence");
      if (jj_2_65(2)) {
        jj_consume_token(SUBJECT);
        if (jj_2_60(2)) {
          jj_consume_token(AUXILIAR_EXPRESSION);
        } else {
          ;
        }
        jj_consume_token(CREATION_VERB);
        if (jj_2_61(2)) {
          jj_consume_token(AUXILIAR_CONNECTOR);
        } else {
          ;
        }
        jj_consume_token(A_THE);
      } else if (jj_2_66(2)) {
        jj_consume_token(SUBJECT_3rd);
        if (jj_2_62(2)) {
          jj_consume_token(AUXILIAR_EXPRESSION);
          jj_consume_token(CREATION_VERB);
        } else if (jj_2_63(2)) {
          jj_consume_token(CREATION_VERB_3rd);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        if (jj_2_64(2)) {
          jj_consume_token(AUXILIAR_CONNECTOR);
        } else {
          ;
        }
        jj_consume_token(A_THE);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("creation_sentence");
    }
  }

/* __ CONTROL __ */

/*
 * ("I", "you"...) ("need to", "want to" | "must", "shall") ("check", "verify") ("also", "in addition")
 * ("I", "you"...) (("needs to", "wants to" | "must", "shall") ("check", "verify") | ("checks", "verifies"))("also", "in addition")
 */
  static final public void control_sentence() throws ParseException {
    trace_call("control_sentence");
    try {
  if(verbose) System.out.println("Starts control_sentence");
      if (jj_2_72(2)) {
        jj_consume_token(SUBJECT);
        if (jj_2_67(2)) {
          jj_consume_token(AUXILIAR_EXPRESSION);
        } else {
          ;
        }
        jj_consume_token(CONTROL_VERB);
        if (jj_2_68(2)) {
          jj_consume_token(AUXILIAR_CONNECTOR);
        } else {
          ;
        }
      } else if (jj_2_73(2)) {
        jj_consume_token(SUBJECT_3rd);
        if (jj_2_69(2)) {
          jj_consume_token(AUXILIAR_EXPRESSION);
          jj_consume_token(CONTROL_VERB);
        } else if (jj_2_70(2)) {
          jj_consume_token(CONTROL_VERB_3rd);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        if (jj_2_71(2)) {
          jj_consume_token(AUXILIAR_CONNECTOR);
        } else {
          ;
        }
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("control_sentence");
    }
  }

/* __ PRINT __ */

/*
 * The print sentence is compulsory. But it can only contain the verb in order to simplify the sketched coding
 * ("print")
 * ("I", "you"...) ("need to", "want to" | "must", "shall") ("print") ("also", "in addition")
 * ("I", "you"...) (("needs to", "wants to" | "must", "shall") ("print") | ("prints"))("also", "in addition") 
 */
  static final public void print_sentence() throws ParseException {
    trace_call("print_sentence");
    try {
  if(verbose) System.out.println("Starts print_sentence");
      if (jj_2_79(2)) {
        jj_consume_token(PRINT_VERB);
      } else if (jj_2_80(2)) {
        jj_consume_token(SUBJECT);
        if (jj_2_74(2)) {
          jj_consume_token(AUXILIAR_EXPRESSION);
        } else {
          ;
        }
        jj_consume_token(PRINT_VERB);
        if (jj_2_75(2)) {
          jj_consume_token(AUXILIAR_CONNECTOR);
        } else {
          ;
        }
      } else if (jj_2_81(2)) {
        jj_consume_token(SUBJECT_3rd);
        if (jj_2_76(2)) {
          jj_consume_token(AUXILIAR_EXPRESSION);
          jj_consume_token(PRINT_VERB);
        } else if (jj_2_77(2)) {
          jj_consume_token(PRINT_VERB_3rd);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        if (jj_2_78(2)) {
          jj_consume_token(AUXILIAR_CONNECTOR);
        } else {
          ;
        }
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("print_sentence");
    }
  }

/* __ READ __ */

/*
 *The read sentence is not needed because it is encapsulated as an expression, so it has no sense to include a phrase in an expression and no phrases for the rest of them.
 *In order to read and store the result in a variable the next expression should be used:
 *
 *String s = read
 */

/* __ RETURN __ */

/*
 * The return sentence is compulsory. But it can only contain the verb in order to simplify the sketched coding.
 * It can only be used in third person, if it stands alone the regular form will be used "return" instead the third person "returns"
 *
 * ("return")
 * ("I", "you"...) (("needs to", "wants to" | "must", "shall") ("return") | ("returns"))
 */
  static final public void return_sentence() throws ParseException {
    trace_call("return_sentence");
    try {
  if(verbose) System.out.println("Starts return_sentence");
      if (jj_2_84(2)) {
        jj_consume_token(RETURN_VERB);
      } else if (jj_2_85(2)) {
        jj_consume_token(SUBJECT_3rd);
        if (jj_2_82(2)) {
          jj_consume_token(AUXILIAR_EXPRESSION);
          jj_consume_token(RETURN_VERB);
        } else if (jj_2_83(2)) {
          jj_consume_token(RETURN_VERB_3rd);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("return_sentence");
    }
  }

/* __ AUXILIAR EXPRESSIONS __ */

/*
 * A parameter list can allways be empty '()'
 *
 * 	(' ( parameter ("," parameter)* )? ')'
 *
 *	The parameter list could be:
 * 		() - empty
 *		(parameter) - one element
 *		(parameter ,parameter ,parameter) -n elements
 *  The parameter list cannot:
 *		(, parameter) - start with connector
 *		(parameter parameter) - have parameters without connector 
 */
  static final public void parameter_list() throws ParseException {
    trace_call("parameter_list");
    try {
  if(verbose) System.out.println("Starts parameter_list");
      jj_consume_token(142);
      if (jj_2_87(2)) {
        parameter();
        label_7:
        while (true) {
          if (jj_2_86(2)) {
            ;
          } else {
            break label_7;
          }
          jj_consume_token(LIST_CONNECTOR);
          parameter();
        }
      } else {
        ;
      }
      jj_consume_token(143);
    } finally {
      trace_return("parameter_list");
    }
  }

/* TYPE ID ([])* */
  static final public void parameter() throws ParseException {
    trace_call("parameter");
    try {
  if(verbose) System.out.println("Starts parameter");
      jj_consume_token(TYPE);
      jj_consume_token(ID);
      if (jj_2_88(2)) {
        jj_consume_token(ARRAY_TOKEN);
      } else {
        ;
      }
    } finally {
      trace_return("parameter");
    }
  }

/*
 * Is like a parameter list but with expressions instead parameters, 
 * much more complex
 *
 * (' ( expression ("," expression)* )? ')'
 */
  static final public void argument_list() throws ParseException {
    trace_call("argument_list");
    try {
  if(verbose) System.out.println("Starts argument_list");
      jj_consume_token(142);
      if (jj_2_90(2)) {
        expression();
        label_8:
        while (true) {
          if (jj_2_89(2)) {
            ;
          } else {
            break label_8;
          }
          jj_consume_token(LIST_CONNECTOR);
          expression();
        }
      } else {
        ;
      }
      jj_consume_token(143);
    } finally {
      trace_return("argument_list");
    }
  }

/*
 * ("equals" | "=") (expression | array_values)
 *
 * It can produce a list of expression or array expressions:
 * 	expresssion
 *  { expression }
 *	{ expression ,expression }
 *	{ expression ,{ expression ,expression } ,expression}
 *
 */
  static final public void array_init() throws ParseException {
    trace_call("array_init");
    try {
  if(verbose) System.out.println("Starts array_init");
      jj_consume_token(146);
      variable_initializer();
      label_9:
      while (true) {
        if (jj_2_91(2)) {
          ;
        } else {
          break label_9;
        }
        jj_consume_token(LIST_CONNECTOR);
        variable_initializer();
      }
      jj_consume_token(147);
    } finally {
      trace_return("array_init");
    }
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  static private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  static private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  static private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  static private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  static private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  static private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  static private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  static private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  static private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  static private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  static private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  static private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  static private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  static private boolean jj_2_37(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_37(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  static private boolean jj_2_38(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_38(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  static private boolean jj_2_39(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_39(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  static private boolean jj_2_40(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_40(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  static private boolean jj_2_41(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_41(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  static private boolean jj_2_42(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_42(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(41, xla); }
  }

  static private boolean jj_2_43(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_43(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(42, xla); }
  }

  static private boolean jj_2_44(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_44(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(43, xla); }
  }

  static private boolean jj_2_45(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_45(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(44, xla); }
  }

  static private boolean jj_2_46(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_46(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(45, xla); }
  }

  static private boolean jj_2_47(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_47(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(46, xla); }
  }

  static private boolean jj_2_48(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_48(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(47, xla); }
  }

  static private boolean jj_2_49(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_49(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(48, xla); }
  }

  static private boolean jj_2_50(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_50(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(49, xla); }
  }

  static private boolean jj_2_51(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_51(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(50, xla); }
  }

  static private boolean jj_2_52(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_52(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(51, xla); }
  }

  static private boolean jj_2_53(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_53(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(52, xla); }
  }

  static private boolean jj_2_54(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_54(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(53, xla); }
  }

  static private boolean jj_2_55(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_55(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(54, xla); }
  }

  static private boolean jj_2_56(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_56(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(55, xla); }
  }

  static private boolean jj_2_57(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_57(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(56, xla); }
  }

  static private boolean jj_2_58(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_58(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(57, xla); }
  }

  static private boolean jj_2_59(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_59(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(58, xla); }
  }

  static private boolean jj_2_60(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_60(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(59, xla); }
  }

  static private boolean jj_2_61(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_61(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(60, xla); }
  }

  static private boolean jj_2_62(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_62(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(61, xla); }
  }

  static private boolean jj_2_63(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_63(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(62, xla); }
  }

  static private boolean jj_2_64(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_64(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(63, xla); }
  }

  static private boolean jj_2_65(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_65(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(64, xla); }
  }

  static private boolean jj_2_66(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_66(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(65, xla); }
  }

  static private boolean jj_2_67(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_67(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(66, xla); }
  }

  static private boolean jj_2_68(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_68(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(67, xla); }
  }

  static private boolean jj_2_69(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_69(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(68, xla); }
  }

  static private boolean jj_2_70(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_70(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(69, xla); }
  }

  static private boolean jj_2_71(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_71(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(70, xla); }
  }

  static private boolean jj_2_72(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_72(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(71, xla); }
  }

  static private boolean jj_2_73(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_73(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(72, xla); }
  }

  static private boolean jj_2_74(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_74(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(73, xla); }
  }

  static private boolean jj_2_75(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_75(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(74, xla); }
  }

  static private boolean jj_2_76(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_76(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(75, xla); }
  }

  static private boolean jj_2_77(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_77(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(76, xla); }
  }

  static private boolean jj_2_78(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_78(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(77, xla); }
  }

  static private boolean jj_2_79(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_79(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(78, xla); }
  }

  static private boolean jj_2_80(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_80(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(79, xla); }
  }

  static private boolean jj_2_81(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_81(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(80, xla); }
  }

  static private boolean jj_2_82(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_82(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(81, xla); }
  }

  static private boolean jj_2_83(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_83(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(82, xla); }
  }

  static private boolean jj_2_84(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_84(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(83, xla); }
  }

  static private boolean jj_2_85(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_85(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(84, xla); }
  }

  static private boolean jj_2_86(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_86(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(85, xla); }
  }

  static private boolean jj_2_87(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_87(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(86, xla); }
  }

  static private boolean jj_2_88(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_88(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(87, xla); }
  }

  static private boolean jj_2_89(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_89(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(88, xla); }
  }

  static private boolean jj_2_90(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_90(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(89, xla); }
  }

  static private boolean jj_2_91(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_91(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(90, xla); }
  }

  static private boolean jj_3R_10() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) jj_scanpos = xsp;
    if (jj_scan_token(CLASS)) return true;
    if (jj_scan_token(CLASS_ID)) return true;
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_scan_token(TYPE)) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3_27() {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_82() {
    if (jj_scan_token(AUXILIAR_EXPRESSION)) return true;
    if (jj_scan_token(RETURN_VERB)) return true;
    return false;
  }

  static private boolean jj_3_87() {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_33()) {
    jj_scanpos = xsp;
    if (jj_3_34()) return true;
    }
    return false;
  }

  static private boolean jj_3_33() {
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3_68() {
    if (jj_scan_token(AUXILIAR_CONNECTOR)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_scan_token(PACKAGE_STATEMENT)) return true;
    return false;
  }

  static private boolean jj_3_63() {
    if (jj_scan_token(CREATION_VERB_3rd)) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_3R_43()) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_45() {
    if (jj_scan_token(READ)) return true;
    return false;
  }

  static private boolean jj_3_61() {
    if (jj_scan_token(AUXILIAR_CONNECTOR)) return true;
    return false;
  }

  static private boolean jj_3_85() {
    if (jj_scan_token(SUBJECT_3rd)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_82()) {
    jj_scanpos = xsp;
    if (jj_3_83()) return true;
    }
    return false;
  }

  static private boolean jj_3R_43() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_84()) {
    jj_scanpos = xsp;
    if (jj_3_85()) return true;
    }
    return false;
  }

  static private boolean jj_3_84() {
    if (jj_scan_token(RETURN_VERB)) return true;
    return false;
  }

  static private boolean jj_3_76() {
    if (jj_scan_token(AUXILIAR_EXPRESSION)) return true;
    if (jj_scan_token(PRINT_VERB)) return true;
    return false;
  }

  static private boolean jj_3_15() {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3_31() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3_38() {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  static private boolean jj_3_26() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3_74() {
    if (jj_scan_token(AUXILIAR_EXPRESSION)) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_3R_42()) return true;
    if (jj_scan_token(142)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_69() {
    if (jj_scan_token(AUXILIAR_EXPRESSION)) return true;
    if (jj_scan_token(CONTROL_VERB)) return true;
    return false;
  }

  static private boolean jj_3_25() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_81() {
    if (jj_scan_token(SUBJECT_3rd)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_76()) {
    jj_scanpos = xsp;
    if (jj_3_77()) return true;
    }
    xsp = jj_scanpos;
    if (jj_3_78()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_80() {
    if (jj_scan_token(SUBJECT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_74()) jj_scanpos = xsp;
    if (jj_scan_token(PRINT_VERB)) return true;
    xsp = jj_scanpos;
    if (jj_3_75()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_37() {
    if (jj_scan_token(UNARY_OPERATOR)) return true;
    return false;
  }

  static private boolean jj_3_44() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_37()) {
    jj_scanpos = xsp;
    if (jj_3_38()) return true;
    }
    return false;
  }

  static private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_79()) {
    jj_scanpos = xsp;
    if (jj_3_80()) {
    jj_scanpos = xsp;
    if (jj_3_81()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_79() {
    if (jj_scan_token(PRINT_VERB)) return true;
    return false;
  }

  static private boolean jj_3_14() {
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3_67() {
    if (jj_scan_token(AUXILIAR_EXPRESSION)) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(142)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3_57() {
    if (jj_scan_token(UNARY_OPERATOR)) return true;
    return false;
  }

  static private boolean jj_3_32() {
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3_62() {
    if (jj_scan_token(AUXILIAR_EXPRESSION)) return true;
    if (jj_scan_token(CREATION_VERB)) return true;
    return false;
  }

  static private boolean jj_3_43() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3_50() {
    if (jj_scan_token(142)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_73() {
    if (jj_scan_token(SUBJECT_3rd)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_69()) {
    jj_scanpos = xsp;
    if (jj_3_70()) return true;
    }
    xsp = jj_scanpos;
    if (jj_3_71()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_60() {
    if (jj_scan_token(AUXILIAR_EXPRESSION)) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_72()) {
    jj_scanpos = xsp;
    if (jj_3_73()) return true;
    }
    return false;
  }

  static private boolean jj_3_72() {
    if (jj_scan_token(SUBJECT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_67()) jj_scanpos = xsp;
    if (jj_scan_token(CONTROL_VERB)) return true;
    xsp = jj_scanpos;
    if (jj_3_68()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_scan_token(ELSE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_32()) jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(142)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3_66() {
    if (jj_scan_token(SUBJECT_3rd)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_62()) {
    jj_scanpos = xsp;
    if (jj_3_63()) return true;
    }
    xsp = jj_scanpos;
    if (jj_3_64()) jj_scanpos = xsp;
    if (jj_scan_token(A_THE)) return true;
    return false;
  }

  static private boolean jj_3_56() {
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_65()) {
    jj_scanpos = xsp;
    if (jj_3_66()) return true;
    }
    return false;
  }

  static private boolean jj_3_13() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3_65() {
    if (jj_scan_token(SUBJECT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_60()) jj_scanpos = xsp;
    if (jj_scan_token(CREATION_VERB)) return true;
    xsp = jj_scanpos;
    if (jj_3_61()) jj_scanpos = xsp;
    if (jj_scan_token(A_THE)) return true;
    return false;
  }

  static private boolean jj_3_59() {
    if (jj_scan_token(DOT_NOTATION)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_30() {
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_30()) jj_scanpos = xsp;
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3_42() {
    if (jj_scan_token(EXPRESSION_MODIFIER)) return true;
    return false;
  }

  static private boolean jj_3_53() {
    if (jj_scan_token(CHAR_LITERAL)) return true;
    return false;
  }

  static private boolean jj_3_23() {
    if (jj_scan_token(STATEMENT_CONNECTOR)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3_24() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_24()) {
    jj_scanpos = xsp;
    if (jj_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_26()) {
    jj_scanpos = xsp;
    if (jj_3_27()) {
    jj_scanpos = xsp;
    if (jj_3_28()) {
    jj_scanpos = xsp;
    if (jj_3_29()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_12() {
    if (jj_scan_token(FINAL_MOD)) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_scan_token(EQUALS)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_55() {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3_49() {
    if (jj_scan_token(TYPE_SPECIAL)) return true;
    if (jj_scan_token(144)) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_58()) {
    jj_scanpos = xsp;
    if (jj_3_59()) return true;
    }
    return false;
  }

  static private boolean jj_3_58() {
    if (jj_scan_token(144)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(145)) return true;
    return false;
  }

  static private boolean jj_3_19() {
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3_41() {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3_52() {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  static private boolean jj_3_21() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_scan_token(OPERATOR)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_scan_token(STATIC_MOD)) return true;
    return false;
  }

  static private boolean jj_3_22() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_22()) jj_scanpos = xsp;
    if (jj_scan_token(TYPE)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3_17() {
    if (jj_scan_token(LIST_CONNECTOR)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_54()) {
    jj_scanpos = xsp;
    if (jj_3_55()) {
    jj_scanpos = xsp;
    if (jj_3_56()) {
    jj_scanpos = xsp;
    if (jj_3_57()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3_54() {
    if (jj_3R_36()) return true;
    return false;
  }

  static private boolean jj_3R_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) return true;
    }
    return false;
  }

  static private boolean jj_3_20() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_29() {
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3_18() {
    if (jj_scan_token(ARRAY_TOKEN)) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_51()) {
    jj_scanpos = xsp;
    if (jj_3_52()) {
    jj_scanpos = xsp;
    if (jj_3_53()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_51() {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_scan_token(VISIBILITY)) return true;
    return false;
  }

  static private boolean jj_3_40() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3_47() {
    if (jj_scan_token(TYPE)) return true;
    if (jj_scan_token(143)) return true;
    return false;
  }

  static private boolean jj_3_16() {
    if (jj_scan_token(ARRAY_TOKEN)) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(EQUALS)) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_scan_token(ABSTRACT_MOD)) return true;
    return false;
  }

  static private boolean jj_3_91() {
    if (jj_scan_token(LIST_CONNECTOR)) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  static private boolean jj_3R_45() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_48()) {
    jj_scanpos = xsp;
    if (jj_3_49()) {
    jj_scanpos = xsp;
    if (jj_3_50()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_48() {
    if (jj_scan_token(CLASS_ID)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_scan_token(TYPE)) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_45()) return true;
    return false;
  }

  static private boolean jj_3_83() {
    if (jj_scan_token(RETURN_VERB_3rd)) return true;
    return false;
  }

  static private boolean jj_3_7() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) return true;
    }
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_scan_token(FINAL_MOD)) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_46()) {
    jj_scanpos = xsp;
    if (jj_3_47()) return true;
    }
    return false;
  }

  static private boolean jj_3_46() {
    if (jj_3R_18()) return true;
    if (jj_scan_token(143)) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_scan_token(VARIABLE)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3_78() {
    if (jj_scan_token(AUXILIAR_CONNECTOR)) return true;
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_34() {
    if (jj_scan_token(142)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_39()) {
    jj_scanpos = xsp;
    if (jj_3_40()) {
    jj_scanpos = xsp;
    if (jj_3_41()) {
    jj_scanpos = xsp;
    if (jj_3_42()) {
    jj_scanpos = xsp;
    if (jj_3_43()) {
    jj_scanpos = xsp;
    if (jj_3_44()) {
    jj_scanpos = xsp;
    if (jj_3_45()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_39() {
    if (jj_scan_token(142)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  static private boolean jj_3_28() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_scan_token(METHOD)) return true;
    if (jj_scan_token(TYPE)) return true;
    return false;
  }

  static private boolean jj_3_89() {
    if (jj_scan_token(LIST_CONNECTOR)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_scan_token(146)) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_scan_token(VISIBILITY)) return true;
    return false;
  }

  static private boolean jj_3_71() {
    if (jj_scan_token(AUXILIAR_CONNECTOR)) return true;
    return false;
  }

  static private boolean jj_3_36() {
    if (jj_3R_31()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_36()) jj_scanpos = xsp;
    if (jj_3R_41()) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_scan_token(CONSTRUCTOR)) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3_90() {
    if (jj_3R_18()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_89()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_88() {
    if (jj_scan_token(ARRAY_TOKEN)) return true;
    return false;
  }

  static private boolean jj_3_77() {
    if (jj_scan_token(PRINT_VERB_3rd)) return true;
    return false;
  }

  static private boolean jj_3_64() {
    if (jj_scan_token(AUXILIAR_CONNECTOR)) return true;
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_scan_token(142)) return true;
    return false;
  }

  static private boolean jj_3_35() {
    if (jj_scan_token(LINKER)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3_86() {
    if (jj_scan_token(LIST_CONNECTOR)) return true;
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_scan_token(CLASS_METHOD_CONNECTOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_10()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3_15()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_75() {
    if (jj_scan_token(AUXILIAR_CONNECTOR)) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_3R_18()) return true;
    if (jj_scan_token(COMPARATOR)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_70() {
    if (jj_scan_token(CONTROL_VERB_3rd)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public SNLTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static private int[] jj_la1_4;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
      jj_la1_init_4();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {};
   }
   private static void jj_la1_init_4() {
      jj_la1_4 = new int[] {};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[91];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public SNL(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SNL(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SNLTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public SNL(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SNLTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public SNL(SNLTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(SNLTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      trace_token(token, "");
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
      trace_token(token, " (in getNextToken)");
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[148];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
          if ((jj_la1_4[i] & (1<<j)) != 0) {
            la1tokens[128+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 148; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static private int trace_indent = 0;
  static private boolean trace_enabled = true;

/** Enable tracing. */
  static final public void enable_tracing() {
    trace_enabled = true;
  }

/** Disable tracing. */
  static final public void disable_tracing() {
    trace_enabled = false;
  }

  static private void trace_call(String s) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Call:   " + s);
    }
    trace_indent = trace_indent + 2;
  }

  static private void trace_return(String s) {
    trace_indent = trace_indent - 2;
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Return: " + s);
    }
  }

  static private void trace_token(Token t, String where) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Consumed token: <" + tokenImage[t.kind]);
      if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
        System.out.print(": \"" + t.image + "\"");
      }
      System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
    }
  }

  static private void trace_scan(Token t1, int t2) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Visited token: <" + tokenImage[t1.kind]);
      if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
        System.out.print(": \"" + t1.image + "\"");
      }
      System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
    }
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 91; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
            case 38: jj_3_39(); break;
            case 39: jj_3_40(); break;
            case 40: jj_3_41(); break;
            case 41: jj_3_42(); break;
            case 42: jj_3_43(); break;
            case 43: jj_3_44(); break;
            case 44: jj_3_45(); break;
            case 45: jj_3_46(); break;
            case 46: jj_3_47(); break;
            case 47: jj_3_48(); break;
            case 48: jj_3_49(); break;
            case 49: jj_3_50(); break;
            case 50: jj_3_51(); break;
            case 51: jj_3_52(); break;
            case 52: jj_3_53(); break;
            case 53: jj_3_54(); break;
            case 54: jj_3_55(); break;
            case 55: jj_3_56(); break;
            case 56: jj_3_57(); break;
            case 57: jj_3_58(); break;
            case 58: jj_3_59(); break;
            case 59: jj_3_60(); break;
            case 60: jj_3_61(); break;
            case 61: jj_3_62(); break;
            case 62: jj_3_63(); break;
            case 63: jj_3_64(); break;
            case 64: jj_3_65(); break;
            case 65: jj_3_66(); break;
            case 66: jj_3_67(); break;
            case 67: jj_3_68(); break;
            case 68: jj_3_69(); break;
            case 69: jj_3_70(); break;
            case 70: jj_3_71(); break;
            case 71: jj_3_72(); break;
            case 72: jj_3_73(); break;
            case 73: jj_3_74(); break;
            case 74: jj_3_75(); break;
            case 75: jj_3_76(); break;
            case 76: jj_3_77(); break;
            case 77: jj_3_78(); break;
            case 78: jj_3_79(); break;
            case 79: jj_3_80(); break;
            case 80: jj_3_81(); break;
            case 81: jj_3_82(); break;
            case 82: jj_3_83(); break;
            case 83: jj_3_84(); break;
            case 84: jj_3_85(); break;
            case 85: jj_3_86(); break;
            case 86: jj_3_87(); break;
            case 87: jj_3_88(); break;
            case 88: jj_3_89(); break;
            case 89: jj_3_90(); break;
            case 90: jj_3_91(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
