/* Generated By:JavaCC: Do not edit this line. SNLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SNLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS_METHOD_CONNECTOR = 5;
  /** RegularExpression Id. */
  int METHOD_STATEMENT_CONNECTOR = 6;
  /** RegularExpression Id. */
  int LIST_CONNECTOR = 7;
  /** RegularExpression Id. */
  int STATEMENT_CONNECTOR = 8;
  /** RegularExpression Id. */
  int PACKAGE_MOD = 9;
  /** RegularExpression Id. */
  int IMPORT_MOD = 10;
  /** RegularExpression Id. */
  int ABSTRACT_MOD = 11;
  /** RegularExpression Id. */
  int STATIC_MOD = 12;
  /** RegularExpression Id. */
  int FINAL_MOD = 13;
  /** RegularExpression Id. */
  int EXTENDS_MOD = 14;
  /** RegularExpression Id. */
  int IMPLEMENTS_MOD = 15;
  /** RegularExpression Id. */
  int AUX_VERB = 16;
  /** RegularExpression Id. */
  int AUX_VERB_3rd = 17;
  /** RegularExpression Id. */
  int MODAL_VERB = 18;
  /** RegularExpression Id. */
  int CLASS = 19;
  /** RegularExpression Id. */
  int END_CLASS = 20;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 21;
  /** RegularExpression Id. */
  int END_CONSTRUCTOR = 22;
  /** RegularExpression Id. */
  int METHOD = 23;
  /** RegularExpression Id. */
  int END_METHOD = 24;
  /** RegularExpression Id. */
  int VARIABLE = 25;
  /** RegularExpression Id. */
  int END_VARIABLE = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int THEN = 29;
  /** RegularExpression Id. */
  int END_IF = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int END_WHILE = 32;
  /** RegularExpression Id. */
  int INSTANCE_OF = 33;
  /** RegularExpression Id. */
  int NEW = 34;
  /** RegularExpression Id. */
  int ARRAY_TOKEN = 35;
  /** RegularExpression Id. */
  int ASSIGN_VERB = 36;
  /** RegularExpression Id. */
  int ASSIGN_VERB_3rd = 37;
  /** RegularExpression Id. */
  int CREATION_VERB = 38;
  /** RegularExpression Id. */
  int CREATION_VERB_3rd = 39;
  /** RegularExpression Id. */
  int CONTROL_VERB = 40;
  /** RegularExpression Id. */
  int CONTROL_VERB_3rd = 41;
  /** RegularExpression Id. */
  int PRINT_VERB = 42;
  /** RegularExpression Id. */
  int PRINT_VERB_3rd = 43;
  /** RegularExpression Id. */
  int READ = 44;
  /** RegularExpression Id. */
  int RETURN_VERB = 45;
  /** RegularExpression Id. */
  int RETURN_VERB_3rd = 46;
  /** RegularExpression Id. */
  int DOT_NOTATION = 47;
  /** RegularExpression Id. */
  int A_THE = 48;
  /** RegularExpression Id. */
  int TO = 49;
  /** RegularExpression Id. */
  int IN = 50;
  /** RegularExpression Id. */
  int AUXILIAR_CONNECTOR = 51;
  /** RegularExpression Id. */
  int SUBJECT = 52;
  /** RegularExpression Id. */
  int SUBJECT_3rd = 53;
  /** RegularExpression Id. */
  int COMPARATOR = 54;
  /** RegularExpression Id. */
  int OPERATOR = 55;
  /** RegularExpression Id. */
  int UNARY_OPERATOR = 56;
  /** RegularExpression Id. */
  int MINUS = 57;
  /** RegularExpression Id. */
  int PLUS = 58;
  /** RegularExpression Id. */
  int LINKER = 59;
  /** RegularExpression Id. */
  int EQUALS = 60;
  /** RegularExpression Id. */
  int AUXILIAR_EXPRESSION = 61;
  /** RegularExpression Id. */
  int AUXILIAR_EXPRESSION3 = 62;
  /** RegularExpression Id. */
  int PACKAGE_STATEMENT = 63;
  /** RegularExpression Id. */
  int VISIBILITY = 64;
  /** RegularExpression Id. */
  int TYPE_SPECIAL = 65;
  /** RegularExpression Id. */
  int BOOLEAN_TOKEN = 66;
  /** RegularExpression Id. */
  int EXPRESSION_MODIFIER = 67;
  /** RegularExpression Id. */
  int COMPARISON_EXPRESSION = 68;
  /** RegularExpression Id. */
  int LANGUAGE_EQUALS_COMPARISON = 69;
  /** RegularExpression Id. */
  int LANGUAGE_COMPARISON = 70;
  /** RegularExpression Id. */
  int COMPARISON_SYMBOLS = 71;
  /** RegularExpression Id. */
  int SYMBOLIC_EQUALS_COMPARISON = 72;
  /** RegularExpression Id. */
  int SYMBOLIC_COMPARISON = 73;
  /** RegularExpression Id. */
  int OPERATION_EXPRESSION = 74;
  /** RegularExpression Id. */
  int OPERATION_SYMBOL = 75;
  /** RegularExpression Id. */
  int UNARY_OPERATION_EXPRESSION = 76;
  /** RegularExpression Id. */
  int UNARY_OPERATION_SYMBOL = 77;
  /** RegularExpression Id. */
  int LINKER_EXPRESSION = 78;
  /** RegularExpression Id. */
  int LINKER_SYMBOL = 79;
  /** RegularExpression Id. */
  int LANGUAGE_NOT = 80;
  /** RegularExpression Id. */
  int LANGUAGE_GREATER = 81;
  /** RegularExpression Id. */
  int LANGUAGE_SMALLER = 82;
  /** RegularExpression Id. */
  int SYMBOLIC_NOT = 83;
  /** RegularExpression Id. */
  int SYMBOLIC_GREATER = 84;
  /** RegularExpression Id. */
  int SYMBOLIC_SMALLER = 85;
  /** RegularExpression Id. */
  int LANGUAGE_MINUS = 86;
  /** RegularExpression Id. */
  int LANGUAGE_PLUS = 87;
  /** RegularExpression Id. */
  int LANGUAGE_TIMES = 88;
  /** RegularExpression Id. */
  int LANGUAGE_DIVIDES = 89;
  /** RegularExpression Id. */
  int SYMBOLIC_MINUS = 90;
  /** RegularExpression Id. */
  int SYMBOLIC_PLUS = 91;
  /** RegularExpression Id. */
  int SYMBOLIC_TIMES = 92;
  /** RegularExpression Id. */
  int SYMBOLIC_DIVIDES = 93;
  /** RegularExpression Id. */
  int LANGUAGE_EQUALS = 94;
  /** RegularExpression Id. */
  int SYMBOLIC_EQUALS = 95;
  /** RegularExpression Id. */
  int LANGUAGE_INCREMENT = 96;
  /** RegularExpression Id. */
  int LANGUAGE_DECREMENT = 97;
  /** RegularExpression Id. */
  int SYMBOLIC_DECREMENT = 98;
  /** RegularExpression Id. */
  int SYMBOLIC_INCREMENT = 99;
  /** RegularExpression Id. */
  int LANGUAGE_AND = 100;
  /** RegularExpression Id. */
  int LANGUAGE_OR = 101;
  /** RegularExpression Id. */
  int SYMBOLIC_OR = 102;
  /** RegularExpression Id. */
  int SYMBOLIC_AND = 103;
  /** RegularExpression Id. */
  int BOOLEAN_EQUALS = 104;
  /** RegularExpression Id. */
  int TRUE = 105;
  /** RegularExpression Id. */
  int FALSE = 106;
  /** RegularExpression Id. */
  int NULL = 107;
  /** RegularExpression Id. */
  int SUPER = 108;
  /** RegularExpression Id. */
  int THIS = 109;
  /** RegularExpression Id. */
  int NORMAL_SUBJECT = 110;
  /** RegularExpression Id. */
  int THIRD_SUBJECT = 111;
  /** RegularExpression Id. */
  int OTHER_SUBJECT = 112;
  /** RegularExpression Id. */
  int IS = 113;
  /** RegularExpression Id. */
  int THAN = 114;
  /** RegularExpression Id. */
  int PUBLIC_MOD = 115;
  /** RegularExpression Id. */
  int PRIVATE_MOD = 116;
  /** RegularExpression Id. */
  int PROTECTED_MOD = 117;
  /** RegularExpression Id. */
  int CHAR = 118;
  /** RegularExpression Id. */
  int BOOLEAN = 119;
  /** RegularExpression Id. */
  int BYTE = 120;
  /** RegularExpression Id. */
  int SHORT = 121;
  /** RegularExpression Id. */
  int INT = 122;
  /** RegularExpression Id. */
  int LONG = 123;
  /** RegularExpression Id. */
  int FLOAT = 124;
  /** RegularExpression Id. */
  int DOUBLE = 125;
  /** RegularExpression Id. */
  int I_SUBJECT = 126;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 127;
  /** RegularExpression Id. */
  int STRING_LITERAL = 128;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 129;
  /** RegularExpression Id. */
  int CLASS_ID = 130;
  /** RegularExpression Id. */
  int ID = 131;
  /** RegularExpression Id. */
  int CONSTANT = 132;
  /** RegularExpression Id. */
  int FLOATING_POINT = 133;
  /** RegularExpression Id. */
  int DIGIT = 134;
  /** RegularExpression Id. */
  int CAP_LETTER = 135;
  /** RegularExpression Id. */
  int ID_BEGIN = 136;
  /** RegularExpression Id. */
  int ID_ANY = 137;
  /** RegularExpression Id. */
  int STRING_VAL = 138;
  /** RegularExpression Id. */
  int CHAR_VAL = 139;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\".\"",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"package\"",
    "\"import\"",
    "\"abstract\"",
    "\"static\"",
    "\"final\"",
    "\"extends\"",
    "\"implements\"",
    "<AUX_VERB>",
    "<AUX_VERB_3rd>",
    "<MODAL_VERB>",
    "\"class\"",
    "\"end-class\"",
    "\"constructor\"",
    "\"end-constructor\"",
    "<METHOD>",
    "<END_METHOD>",
    "<VARIABLE>",
    "<END_VARIABLE>",
    "\"if\"",
    "\"else\"",
    "\"then\"",
    "\"end-if\"",
    "\"while\"",
    "\"end-while\"",
    "\"instance_of\"",
    "\"new\"",
    "<ARRAY_TOKEN>",
    "<ASSIGN_VERB>",
    "<ASSIGN_VERB_3rd>",
    "<CREATION_VERB>",
    "<CREATION_VERB_3rd>",
    "<CONTROL_VERB>",
    "<CONTROL_VERB_3rd>",
    "\"print\"",
    "\"prints\"",
    "\"read\"",
    "\"return\"",
    "\"returns\"",
    "\"->\"",
    "<A_THE>",
    "\"to\"",
    "\"in\"",
    "<AUXILIAR_CONNECTOR>",
    "<SUBJECT>",
    "<SUBJECT_3rd>",
    "<COMPARATOR>",
    "<OPERATOR>",
    "<UNARY_OPERATOR>",
    "<MINUS>",
    "<PLUS>",
    "<LINKER>",
    "<EQUALS>",
    "<AUXILIAR_EXPRESSION>",
    "<AUXILIAR_EXPRESSION3>",
    "<PACKAGE_STATEMENT>",
    "<VISIBILITY>",
    "<TYPE_SPECIAL>",
    "<BOOLEAN_TOKEN>",
    "<EXPRESSION_MODIFIER>",
    "<COMPARISON_EXPRESSION>",
    "<LANGUAGE_EQUALS_COMPARISON>",
    "<LANGUAGE_COMPARISON>",
    "<COMPARISON_SYMBOLS>",
    "<SYMBOLIC_EQUALS_COMPARISON>",
    "<SYMBOLIC_COMPARISON>",
    "<OPERATION_EXPRESSION>",
    "<OPERATION_SYMBOL>",
    "<UNARY_OPERATION_EXPRESSION>",
    "<UNARY_OPERATION_SYMBOL>",
    "<LINKER_EXPRESSION>",
    "<LINKER_SYMBOL>",
    "\"not\"",
    "\"greater\"",
    "\"smaller\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\"minus\"",
    "\"plus\"",
    "\"times\"",
    "\"divides\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"equals\"",
    "\"=\"",
    "\"increment\"",
    "\"decrement\"",
    "\"--\"",
    "\"++\"",
    "\"and\"",
    "\"or\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"super\"",
    "\"this\"",
    "<NORMAL_SUBJECT>",
    "<THIRD_SUBJECT>",
    "<OTHER_SUBJECT>",
    "\"is\"",
    "\"than\"",
    "\"public\"",
    "\"private\"",
    "\"protected\"",
    "\"char\"",
    "\"boolean\"",
    "\"byte\"",
    "\"short\"",
    "\"int\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "\"I\"",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<CHAR_LITERAL>",
    "<CLASS_ID>",
    "<ID>",
    "<CONSTANT>",
    "\". \"",
    "<DIGIT>",
    "<CAP_LETTER>",
    "<ID_BEGIN>",
    "<ID_ANY>",
    "<STRING_VAL>",
    "<CHAR_VAL>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
  };

}
