/* Generated By:JavaCC: Do not edit this line. SNLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SNLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS_METHOD_CONNECTOR = 9;
  /** RegularExpression Id. */
  int METHOD_STATEMENT_CONNECTOR = 10;
  /** RegularExpression Id. */
  int LIST_CONNECTOR = 11;
  /** RegularExpression Id. */
  int STATEMENT_CONNECTOR = 12;
  /** RegularExpression Id. */
  int PACKAGE_MOD = 13;
  /** RegularExpression Id. */
  int IMPORT_MOD = 14;
  /** RegularExpression Id. */
  int ABSTRACT_MOD = 15;
  /** RegularExpression Id. */
  int STATIC_MOD = 16;
  /** RegularExpression Id. */
  int FINAL_MOD = 17;
  /** RegularExpression Id. */
  int EXTENDS_MOD = 18;
  /** RegularExpression Id. */
  int IMPLEMENTS_MOD = 19;
  /** RegularExpression Id. */
  int AUX_VERB = 20;
  /** RegularExpression Id. */
  int AUX_VERB_3rd = 21;
  /** RegularExpression Id. */
  int MODAL_VERB = 22;
  /** RegularExpression Id. */
  int CLASS = 23;
  /** RegularExpression Id. */
  int END_CLASS = 24;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 25;
  /** RegularExpression Id. */
  int END_CONSTRUCTOR = 26;
  /** RegularExpression Id. */
  int METHOD = 27;
  /** RegularExpression Id. */
  int END_METHOD = 28;
  /** RegularExpression Id. */
  int VARIABLE = 29;
  /** RegularExpression Id. */
  int END_VARIABLE = 30;
  /** RegularExpression Id. */
  int IF = 31;
  /** RegularExpression Id. */
  int ELSE = 32;
  /** RegularExpression Id. */
  int THEN = 33;
  /** RegularExpression Id. */
  int END_IF = 34;
  /** RegularExpression Id. */
  int WHILE = 35;
  /** RegularExpression Id. */
  int END_WHILE = 36;
  /** RegularExpression Id. */
  int INSTANCE_OF = 37;
  /** RegularExpression Id. */
  int NEW = 38;
  /** RegularExpression Id. */
  int ARRAY_TOKEN = 39;
  /** RegularExpression Id. */
  int ASSIGN_VERB = 40;
  /** RegularExpression Id. */
  int ASSIGN_VERB_3rd = 41;
  /** RegularExpression Id. */
  int CREATION_VERB = 42;
  /** RegularExpression Id. */
  int CREATION_VERB_3rd = 43;
  /** RegularExpression Id. */
  int CONTROL_VERB = 44;
  /** RegularExpression Id. */
  int CONTROL_VERB_3rd = 45;
  /** RegularExpression Id. */
  int PRINT_VERB = 46;
  /** RegularExpression Id. */
  int PRINT_VERB_3rd = 47;
  /** RegularExpression Id. */
  int READ = 48;
  /** RegularExpression Id. */
  int RETURN_VERB = 49;
  /** RegularExpression Id. */
  int RETURN_VERB_3rd = 50;
  /** RegularExpression Id. */
  int DOT_NOTATION = 51;
  /** RegularExpression Id. */
  int A_THE = 52;
  /** RegularExpression Id. */
  int TO = 53;
  /** RegularExpression Id. */
  int IN = 54;
  /** RegularExpression Id. */
  int AUXILIAR_CONNECTOR = 55;
  /** RegularExpression Id. */
  int SUBJECT = 56;
  /** RegularExpression Id. */
  int SUBJECT_3rd = 57;
  /** RegularExpression Id. */
  int COMPARATOR = 58;
  /** RegularExpression Id. */
  int OPERATOR = 59;
  /** RegularExpression Id. */
  int UNARY_OPERATOR = 60;
  /** RegularExpression Id. */
  int MINUS = 61;
  /** RegularExpression Id. */
  int PLUS = 62;
  /** RegularExpression Id. */
  int LINKER = 63;
  /** RegularExpression Id. */
  int EQUALS = 64;
  /** RegularExpression Id. */
  int AUXILIAR_EXPRESSION = 65;
  /** RegularExpression Id. */
  int AUXILIAR_EXPRESSION3 = 66;
  /** RegularExpression Id. */
  int PACKAGE_STATEMENT = 67;
  /** RegularExpression Id. */
  int VISIBILITY = 68;
  /** RegularExpression Id. */
  int TYPE_SPECIAL = 69;
  /** RegularExpression Id. */
  int BOOLEAN_TOKEN = 70;
  /** RegularExpression Id. */
  int EXPRESSION_MODIFIER = 71;
  /** RegularExpression Id. */
  int COMPARISON_EXPRESSION = 72;
  /** RegularExpression Id. */
  int LANGUAGE_EQUALS_COMPARISON = 73;
  /** RegularExpression Id. */
  int LANGUAGE_COMPARISON = 74;
  /** RegularExpression Id. */
  int COMPARISON_SYMBOLS = 75;
  /** RegularExpression Id. */
  int SYMBOLIC_EQUALS_COMPARISON = 76;
  /** RegularExpression Id. */
  int SYMBOLIC_COMPARISON = 77;
  /** RegularExpression Id. */
  int OPERATION_EXPRESSION = 78;
  /** RegularExpression Id. */
  int OPERATION_SYMBOL = 79;
  /** RegularExpression Id. */
  int UNARY_OPERATION_EXPRESSION = 80;
  /** RegularExpression Id. */
  int UNARY_OPERATION_SYMBOL = 81;
  /** RegularExpression Id. */
  int LINKER_EXPRESSION = 82;
  /** RegularExpression Id. */
  int LINKER_SYMBOL = 83;
  /** RegularExpression Id. */
  int LANGUAGE_NOT = 84;
  /** RegularExpression Id. */
  int LANGUAGE_GREATER = 85;
  /** RegularExpression Id. */
  int LANGUAGE_SMALLER = 86;
  /** RegularExpression Id. */
  int SYMBOLIC_NOT = 87;
  /** RegularExpression Id. */
  int SYMBOLIC_GREATER = 88;
  /** RegularExpression Id. */
  int SYMBOLIC_SMALLER = 89;
  /** RegularExpression Id. */
  int LANGUAGE_MINUS = 90;
  /** RegularExpression Id. */
  int LANGUAGE_PLUS = 91;
  /** RegularExpression Id. */
  int LANGUAGE_TIMES = 92;
  /** RegularExpression Id. */
  int LANGUAGE_DIVIDES = 93;
  /** RegularExpression Id. */
  int SYMBOLIC_MINUS = 94;
  /** RegularExpression Id. */
  int SYMBOLIC_PLUS = 95;
  /** RegularExpression Id. */
  int SYMBOLIC_TIMES = 96;
  /** RegularExpression Id. */
  int SYMBOLIC_DIVIDES = 97;
  /** RegularExpression Id. */
  int LANGUAGE_EQUALS = 98;
  /** RegularExpression Id. */
  int SYMBOLIC_EQUALS = 99;
  /** RegularExpression Id. */
  int LANGUAGE_INCREMENT = 100;
  /** RegularExpression Id. */
  int LANGUAGE_DECREMENT = 101;
  /** RegularExpression Id. */
  int SYMBOLIC_DECREMENT = 102;
  /** RegularExpression Id. */
  int SYMBOLIC_INCREMENT = 103;
  /** RegularExpression Id. */
  int LANGUAGE_AND = 104;
  /** RegularExpression Id. */
  int LANGUAGE_OR = 105;
  /** RegularExpression Id. */
  int SYMBOLIC_OR = 106;
  /** RegularExpression Id. */
  int SYMBOLIC_AND = 107;
  /** RegularExpression Id. */
  int BOOLEAN_EQUALS = 108;
  /** RegularExpression Id. */
  int TRUE = 109;
  /** RegularExpression Id. */
  int FALSE = 110;
  /** RegularExpression Id. */
  int NULL = 111;
  /** RegularExpression Id. */
  int SUPER = 112;
  /** RegularExpression Id. */
  int THIS = 113;
  /** RegularExpression Id. */
  int NORMAL_SUBJECT = 114;
  /** RegularExpression Id. */
  int THIRD_SUBJECT = 115;
  /** RegularExpression Id. */
  int OTHER_SUBJECT = 116;
  /** RegularExpression Id. */
  int IS = 117;
  /** RegularExpression Id. */
  int THAN = 118;
  /** RegularExpression Id. */
  int PUBLIC_MOD = 119;
  /** RegularExpression Id. */
  int PRIVATE_MOD = 120;
  /** RegularExpression Id. */
  int PROTECTED_MOD = 121;
  /** RegularExpression Id. */
  int CHAR = 122;
  /** RegularExpression Id. */
  int BOOLEAN = 123;
  /** RegularExpression Id. */
  int BYTE = 124;
  /** RegularExpression Id. */
  int SHORT = 125;
  /** RegularExpression Id. */
  int INT = 126;
  /** RegularExpression Id. */
  int LONG = 127;
  /** RegularExpression Id. */
  int FLOAT = 128;
  /** RegularExpression Id. */
  int DOUBLE = 129;
  /** RegularExpression Id. */
  int VOID = 130;
  /** RegularExpression Id. */
  int I_SUBJECT = 131;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 132;
  /** RegularExpression Id. */
  int STRING_LITERAL = 133;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 134;
  /** RegularExpression Id. */
  int CLASS_ID = 135;
  /** RegularExpression Id. */
  int ID = 136;
  /** RegularExpression Id. */
  int CONSTANT = 137;
  /** RegularExpression Id. */
  int FLOATING_POINT = 138;
  /** RegularExpression Id. */
  int DIGIT = 139;
  /** RegularExpression Id. */
  int CAP_LETTER = 140;
  /** RegularExpression Id. */
  int ID_BEGIN = 141;
  /** RegularExpression Id. */
  int ID_ANY = 142;
  /** RegularExpression Id. */
  int STRING_VAL = 143;
  /** RegularExpression Id. */
  int CHAR_VAL = 144;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int InnerComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"--\"",
    "\"--\"",
    "\"-!\"",
    "<token of kind 4>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<CLASS_METHOD_CONNECTOR>",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"package\"",
    "\"import\"",
    "\"abstract\"",
    "\"static\"",
    "\"final\"",
    "\"extends\"",
    "\"implements\"",
    "<AUX_VERB>",
    "<AUX_VERB_3rd>",
    "<MODAL_VERB>",
    "\"class\"",
    "\"end_class\"",
    "\"constructor\"",
    "\"end_constructor\"",
    "<METHOD>",
    "<END_METHOD>",
    "<VARIABLE>",
    "<END_VARIABLE>",
    "\"if\"",
    "\"else\"",
    "\"then\"",
    "\"end_if\"",
    "\"while\"",
    "\"end_while\"",
    "\"instance_of\"",
    "\"new\"",
    "<ARRAY_TOKEN>",
    "<ASSIGN_VERB>",
    "<ASSIGN_VERB_3rd>",
    "<CREATION_VERB>",
    "<CREATION_VERB_3rd>",
    "<CONTROL_VERB>",
    "<CONTROL_VERB_3rd>",
    "\"print\"",
    "\"prints\"",
    "\"read\"",
    "\"return\"",
    "\"returns\"",
    "\"->\"",
    "<A_THE>",
    "\"to\"",
    "\"in\"",
    "<AUXILIAR_CONNECTOR>",
    "<SUBJECT>",
    "<SUBJECT_3rd>",
    "<COMPARATOR>",
    "<OPERATOR>",
    "<UNARY_OPERATOR>",
    "<MINUS>",
    "<PLUS>",
    "<LINKER>",
    "<EQUALS>",
    "<AUXILIAR_EXPRESSION>",
    "<AUXILIAR_EXPRESSION3>",
    "<PACKAGE_STATEMENT>",
    "<VISIBILITY>",
    "<TYPE_SPECIAL>",
    "<BOOLEAN_TOKEN>",
    "<EXPRESSION_MODIFIER>",
    "<COMPARISON_EXPRESSION>",
    "<LANGUAGE_EQUALS_COMPARISON>",
    "<LANGUAGE_COMPARISON>",
    "<COMPARISON_SYMBOLS>",
    "<SYMBOLIC_EQUALS_COMPARISON>",
    "<SYMBOLIC_COMPARISON>",
    "<OPERATION_EXPRESSION>",
    "<OPERATION_SYMBOL>",
    "<UNARY_OPERATION_EXPRESSION>",
    "<UNARY_OPERATION_SYMBOL>",
    "<LINKER_EXPRESSION>",
    "<LINKER_SYMBOL>",
    "\"not\"",
    "\"greater\"",
    "\"smaller\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\"minus\"",
    "\"plus\"",
    "\"times\"",
    "\"divides\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"equal\"",
    "\"=\"",
    "\"increment\"",
    "\"decrement\"",
    "\"--\"",
    "\"++\"",
    "\"and\"",
    "\"or\"",
    "\"||\"",
    "\"&&\"",
    "<BOOLEAN_EQUALS>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"super\"",
    "\"this\"",
    "<NORMAL_SUBJECT>",
    "<THIRD_SUBJECT>",
    "<OTHER_SUBJECT>",
    "\"is\"",
    "\"than\"",
    "\"public\"",
    "\"private\"",
    "\"protected\"",
    "\"char\"",
    "\"boolean\"",
    "\"byte\"",
    "\"short\"",
    "\"int\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "<VOID>",
    "\"I\"",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<CHAR_LITERAL>",
    "<CLASS_ID>",
    "<ID>",
    "<CONSTANT>",
    "\". \"",
    "<DIGIT>",
    "<CAP_LETTER>",
    "<ID_BEGIN>",
    "<ID_ANY>",
    "<STRING_VAL>",
    "<CHAR_VAL>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
  };

}
